### PR TITLE
[BUGFIX canary] Prevent unknown input types from erroring.

### LINKED ISSUE #10458: Internet Explorer + Ember 1.11 + {{input type="time"}} = Error: Invalid argument
http://emberjs.jsbin.com/wikapibipa/1/edit?html,js,output

### PR DESCRIPTION
**Pull request by rwjblue**
Browsers support various values for `type`, and generally auto-correct to just `"text"` if an unknown type is set via standard HTML.

Unfortunately, the same auto-correct behavior does not apply when setting the attribute directly, and in some circumstances throw an error where the type is not valid.

Specifically, the following throws an error in IE10:

``` javascript
var e = document.createElement('input');

e.type = 'search';
```

However the following HTML would auto-correct to `"text"`:

``` html
<input type="search">
```

---

This PR adds a feature detect to see if a given type can be set to `input`. If setting the type results in the value, then we use it otherwise we default to `"text"`.

Fixes #10458.

### CODE REVIEW

File: packages/ember-views/lib/views/text_field.js [hunk 1]
```diff
@@ -2,9 +2,35 @@
...
+
+  // if running in outside of a browser always return the
+  // original type
+  if (!environment.hasDom) {
+    inputTypes[type] = type;
+
+    return type;
+  }
+
+  var input = document.createElement('input');
```
Comment (stefanpenner) [inline packages/ember-views/lib/views/text_field.js]: we should likely just create this element once, not once per type.

File: packages/ember-views/lib/views/text_field.js [hunk 2]
```diff
@@ -73,7 +99,15 @@ export default Component.extend(TextSupport, {
     @type String
     @default "text"
   */
-  type: "text",
+  type: computed(function(key, value) {
+    var type = 'text';
```
Comment (stefanpenner) [inline packages/ember-views/lib/views/text_field.js]: should we use the new getter/setter syntax, or is that now yet ready?

File: packages/ember-views/lib/views/text_field.js (hunk 1 above)
Comment (rwjblue) [inline packages/ember-views/lib/views/text_field.js]: Good point, done.

File: packages/ember-views/lib/views/text_field.js (hunk 2 above)
Comment (rwjblue) [inline packages/ember-views/lib/views/text_field.js]: It isn't enabled yet, I could write it both ways, and use the new one if enabled though.  Slightly more work, but easier later.

Comment (stefanpenner) [inline packages/ember-views/lib/views/text_field.js]: your call, we can wait :)

Comment (rwjblue) [inline packages/ember-views/lib/views/text_field.js]: Done.

**Comment by stefanpenner** [comment]
LGTM

**Comment by mixonic** [comment]
Thanks Robert.

**Comment by jayphelps** [comment]
@rwjblue I think this can actually be pulled out if https://github.com/tildeio/htmlbars/pull/355 lands and input#type is added to the [list of bad pairs](https://github.com/tildeio/htmlbars/pull/355/files#diff-c27685a194e08a9a3df40386a9c4d577R35) to use `setAttribute` instead? That way the HTML and attribute is still correctly set as the unknown type, but the property is `text`. c?

**Comment by rwjblue** [comment]
C
