### PR TITLE
[BUGFIX beta] Cleanup view teardown.

### LINKED ISSUE #12080: parentView undefined during willDestroyElement
This happens at least since v1.13.5. When changing to an older v1.11.1, assert never fails.

jsbin: http://emberjs.jsbin.com/lireho/edit?html,js,output

It would make sense that the parentView is still present since the event is called before the element gets destroyed.
So does this work as intended?

### PR DESCRIPTION
**Pull request by krisselden**
- [x] Add tests to ensure `.parentView` is available in all hooks.
- [x] Add tests to ensure `.element` is available in appropriate hooks.
- [x] add tests that assure counts of hooks in all dynamic scenarios
- [x] add regression tests
  - [x] `willDestroyElement` is called for components invoked from the `{{else}}` hook of an `{{#each` https://github.com/emberjs/ember.js/issues/12716.
  - [x] `this.parentView` is available in `willDestroyElement` https://github.com/emberjs/ember.js/issues/12080.
  - [x] `willDestroyElement` is called before actual destruction for components rendered with `{{component` helper.

This should fix #12080 #12716 and #13028

### CODE REVIEW

File: packages/ember-glimmer/lib/renderer.js [hunk 1]
```diff
@@ -192,7 +192,9 @@ class Renderer {
       _renderResult.destroy();
     }
 
-    view.destroy();
+    if (!view.isDestroying) {
```
Comment (stefanpenner) [inline packages/ember-glimmer/lib/renderer.js]: should we guard against both `isDestroying` and `isDestroyed`

File: packages/ember-htmlbars/lib/component.js [hunk 2]
```diff
@@ -465,7 +471,8 @@ const Component = View.extend(TargetActionSupport, ActionSupport, {
 Component[NAME_KEY] = 'Ember.Component';
 
 Component.reopenClass({
-  isComponentFactory: true
+  isComponentFactory: true,
+  positionalParams: []
```
Comment (stefanpenner) [inline packages/ember-htmlbars/lib/component.js]: tell me more

File: packages/ember-views/lib/views/states/in_dom.js [hunk 3]
```diff
@@ -27,7 +27,9 @@ assign(inDOM, {
   },
 
   exit(view) {
-    view._unregister();
+    if (view.tagName !== '') {
```
Comment (stefanpenner) [inline packages/ember-views/lib/views/states/in_dom.js]: this may need a test

File: packages/ember-glimmer/lib/renderer.js (hunk 1 above)
Comment (krisselden) [inline packages/ember-glimmer/lib/renderer.js]: we don't unset isDestroying when we set isDestroyed but I can add that

File: packages/ember-htmlbars/lib/component.js (hunk 2 above)
Comment (krisselden) [inline packages/ember-htmlbars/lib/component.js]: so I mean to move the doc here too, but the issue is `if (positionalParams) {` will optimize to false because this is uncommon but not exceptional and the branch deopts, I was doing a lot of clean as I go, I can remove that stuff and make it a separate PR

Comment (krisselden) [inline packages/ember-htmlbars/lib/component.js]: this is the same with all the hooks

Comment (stefanpenner) [inline packages/ember-htmlbars/lib/component.js]: ah, and this is already `prototype` only type thing. Seems good thanks

File: packages/ember-glimmer/lib/renderer.js (hunk 1 above)
Comment (stefanpenner) [inline packages/ember-glimmer/lib/renderer.js]: ah, then its not needed. Seems good

**Comment by rwjblue** [comment]
OK, I added regression tests for the various scenarios that were tweaked here (including the specific issues linked in the description).

**Comment by krisselden** [comment]
@rwjblue thank you so much for doing these tests.
