### PR TITLE
If syntax error message

### LINKED ISSUE #16322: Unhelpful syntax error message
I just updated to ember 3 and got the following error (everything else is working fine):

```
Uncaught Error: SYNTAX ERROR: #if requires a single argument
```

Considering the size of the codebase, I can't figure out where this error comes from (already looked at all `#if` so I suppose I missed one...) and didn't find out how or where it was generated in this repository so I can't send a PR either.

Could you add the full `#if` syntax please? It'd be really helpful...

### PR DESCRIPTION
**Pull request by AlexTraher**
This (hopefully) resolves [issue 16322](https://github.com/emberjs/ember.js/issues/16322) regarding an unclear error message when passing an incorrect number of arguments to an `if` helper.

### CODE REVIEW

File: packages/ember-template-compiler/tests/plugins/assert-if-helper-without-arguments-test.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
+import { compile } from '../../index';
+import { moduleFor, AbstractTestCase } from 'internal-test-helpers';
+
+moduleFor('ember-template-compiler: assert-if-helper-without-argument', class extends AbstractTestCase {
+  [`@test block if helper expects one argument`](assert) {
+    assert.throws(() => {
```
Comment (rwjblue) [inline packages/ember-template-compiler/tests/plugins/assert-if-helper-without-arguments-test.js]: I believe this should be `expectAssertion`

File: packages/ember-template-compiler/tests/plugins/assert-if-helper-without-arguments-test.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+       compile(`{{#if}}aVal{{/if}}`, {
+        moduleName: 'baz/foo-bar'
+      });
+    }, `#if requires a single argument. ('baz/foo-bar' @ L1:C0) `);
+
+    assert.throws(() => {
```
Comment (rwjblue) [inline packages/ember-template-compiler/tests/plugins/assert-if-helper-without-arguments-test.js]: `expectAssertion`

File: packages/ember-template-compiler/tests/plugins/assert-if-helper-without-arguments-test.js [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+    expectAssertion(() => {
+      compile(`{{#if}}aVal{{/if}}`, {
+        moduleName: 'baz/foo-bar'
+      });
+    }, `#if requires a single argument. ('baz/foo-bar' @ L1:C0) `);
+  }
+
+  [`@test inline if helper expects between one and three arguments`](assert) {
+    assert.throws(() => {
```
Comment (rwjblue) [inline packages/ember-template-compiler/tests/plugins/assert-if-helper-without-arguments-test.js]: `expectAssertion`

**Review by rwjblue — CHANGES_REQUESTED** [review]
Looking good, thanks for picking this up!

I left some inline comments (mostly just moving from `assert.throws` to `expectAssertion` which should fix an issue with the production build), but would also like to see some tests added confirming a few additional scenarios work:

* `{{some-thing foo=(if)}}` should error
* `{{some-thing foo=(if foo bar baz)}}` should not error
* `{{if foo bar baz}}` should not error

File: packages/ember-template-compiler/lib/plugins/assert-if-helper-without-arguments.js [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+    }
+  };
+}
+
+function assertMessage(original) {
+  return `${original} requires a single argument.`;
+}
+
+function isInvalidInlineIf(node) {
+  return node.path.original === 'if' && (!node.params || node.params.length < 1);
```
Comment (rwjblue) [inline packages/ember-template-compiler/lib/plugins/assert-if-helper-without-arguments.js]: Should we make the minimum length be 2?  I'm not sure how something like `{{if something}}` is useful (e.g. if there is no truthy or falsey argument, what is even happening?)...

What do you think @AlexTraher?

Comment (AlexTraher) [reply packages/ember-template-compiler/lib/plugins/assert-if-helper-without-arguments.js]: @rwjblue Yeah agreed - I like the idea it fails loudly.

**Comment by rwjblue** [comment]
Looks great! Can you squash down to a single commit?

**Review by rwjblue — APPROVED** [review]
Awesome job here, thank you very much!

**Comment by AlexTraher** [comment]
Thanks for making the time to give feedback! :+1:
