### PR TITLE
[BUGFIX] Fix missing value attribute on radio/checkbox inputs bound to empty string 

### LINKED ISSUE #19219: [Bug?] input[type=radio] value attr is not rendered if binded to empty string (FF only)
### 🐞 Describe the Bug
`<input type="radio" value={{""}} data-foo={{""}}>` results in 
`<input type="radio" data-foo="">` in FF. The `value` attribute is missing.

In Chrome it renders as expected: `<input type="radio" data-foo="" value="">`.

### 🔬 Minimal Reproduction

https://ember-twiddle.com/5d4f5d525e3108d3a4b09142a61fe0a2?openFiles=templates.application%5C.hbs%2C

It's also reproducible on [glimmer-playground](https://glimmer-playground.netlify.app/?app=JTdCJTIyY29tcG9uZW50cyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJHbGltbWVyQXBwJTIyJTJDJTIydGVtcGxhdGUlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRkdsaW1tZXJBcHAlMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTNDaW5wdXQlMjB0eXBlJTNEJTVDJTIycmFkaW8lNUMlMjIlMjB2YWx1ZSUzRCU3QiU3QiU1QyUyMiU1QyUyMiU3RCU3RCUyMGRhdGEtZm9vJTNEJTdCJTdCJTVDJTIyJTVDJTIyJTdEJTdEJTNFJTIyJTdEJTJDJTIyY29tcG9uZW50JTIyJTNBJTdCJTIyZmlsZU5hbWUlMjIlM0ElMjJzcmMlMkZ1aSUyRmNvbXBvbmVudHMlMkZHbGltbWVyQXBwJTJGY29tcG9uZW50LnRzJTIyJTJDJTIyc291cmNlVGV4dCUyMiUzQSUyMmltcG9ydCUyMENvbXBvbmVudCUyMGZyb20lMjAnJTQwZ2xpbW1lciUyRmNvbXBvbmVudCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyMGV4dGVuZHMlMjBDb21wb25lbnQlMjAlN0IlNUNuJTdEJTIyJTdEJTdEJTVEJTJDJTIyaGVscGVycyUyMiUzQSU1QiU1RCU3RA==).

### 😕 Actual Behavior
The `value` attribute is missing in FF.

### 🤔 Expected Behavior
The `value` attribute is present and has an empty value.

### 🌍 Environment

- Ember: 3.18.1
- OS: linux
- Browser: FF 80.0.1

### ➕ Additional Context
Actually, it a problem, because 
```hbs
<input type="radio" onchange={{action (mut currentValue) value="target.value"}}>
``` 
will set `"on"` to the `currentValue` instead of an empty string, if `value` attribute is missing.

### PR DESCRIPTION
**Pull request by johanrd**
- Fixes `<input type="radio" value={{""}}>` not rendering the value attribute
  - Adds regression test

### Root cause

  Glimmer applies dynamic attributes (value) before static attributes (type) during element construction. The sequence is:

  1. input.value = '' — no-op, '' is already the default for type="text"
  2. input.type = 'radio' — default value changes to "on", browser doesn't retroactively reflect the earlier empty string

  This was originally reported as Firefox-only but is now reproducible in Chrome 145+.

### Fix

  When value is explicitly set to '' on an `<input>`, also call setAttribute('value', '') in addition to the property setter. This ensures the attribute is present in the DOM regardless of attribute application order. The `<textarea>` case is excluded since it doesn't use a value attribute.

  Closes #19219
  
  Cowritten by Claude

### CODE REVIEW

File: packages/@ember/-internals/glimmer/tests/integration/input-test.js [hunk 1]
```diff
@@ -201,6 +201,30 @@ moduleFor(
       this.assertValue('hola', 'Value is used');
     }
 
+    ['@test GH19219 input[type=radio] value attribute is rendered when bound to empty string']() {
+      this.render(`<input type="radio" value={{this.value}}>`, { value: '' });
+
+      this.assert.strictEqual(
+        this.inputElement().getAttribute('value'),
```
Comment (NullVoxPopuli) [inline packages/@ember/-internals/glimmer/tests/integration/input-test.js:208]: What did this return before the fix?

Comment (johanrd) [reply packages/@ember/-internals/glimmer/tests/integration/input-test.js:208]: - actual: null                                                                                                                                                                                            
  - expected: "" (empty string)                                                                                                                                                                             
  - message: "value attribute is present and empty on initial render"

**Review by NullVoxPopuli — APPROVED** [review]

**Review by NullVoxPopuli — APPROVED** [review]
