### PR TITLE
[BUGFIX lts] Ensure event dispatcher is a singleton

### LINKED ISSUE #440: Tagless components issue within routeless engines
It seems that there are some event binding issues when using tagless components within a routeless engine.

Repro: https://github.com/mike183/engines-tagless-component-issue

**Steps to reproduce**
1. Clone the above repo
2. `yarn`
3. `ember serve`
4. Navigate to `http://localhost:4200/`
5. Click `Route #1` link at the top of the page
6. Click the 'Click Me' button several times and observe the clicks counter increment
7. Click `Route #2` link at the top of the page
8. Click `Route #1` link at the top of the page
9. Click the 'Click Me' button again, you'll notice that it no longer increments the counter

When inspecting the 'Click Me' button in the Chrome inspector, it appears that events aren't being registered after the tagless component has been rendered, so I'm not exactly sure where the issue could be.

If you comment out [this line](https://github.com/mike183/engines-tagless-component-issue/blob/master/lib/routeless-engine/addon/components/tagless-component.js#L5), making the component no longer tagless, everything begins to work as expected.

### PR DESCRIPTION
**Pull request by mike183**
This PR fixes https://github.com/ember-engines/ember-engines/issues/440

I have added a test that follows the reproduction steps in the issue above, though the test isn't failing without the change, so I'm not sure if either I'm doing something wrong, or if there is something about the test environment which is masking the issue.

FWIW I have verified that this fix is working in the reproduction app via `yarn link`.

cc/ @rwjblue

### CODE REVIEW

**Comment by mike183** [comment]
Can somebody give CI a kick please 🙂

File: packages/ember-glimmer/tests/integration/mount-test.js [hunk 1]
```diff
@@ -188,6 +188,56 @@ moduleFor('{{mount}} test', class extends ApplicationTest {
...
+    }));
+
+    return this.visit('/engine-teardown').then(() => {
+      this.assertComponentElement(this.firstChild, { content: 'Clicks: 0 <button id="increment-engine-total-clicks">Increment</button>' });
+
+      this.runTask(() => this.$("#increment-engine-total-clicks").click());
+
+      this.assertComponentElement(this.firstChild, { content: 'Clicks: 1 <button id="increment-engine-total-clicks">Increment</button>' });
+
+      return this.visit('/engine-teardown-engine').then(() => {
```
Comment (rwjblue) [inline packages/ember-glimmer/tests/integration/mount-test.js]: Can you swap this to using links that are clicked (instead of this.visit which I believe creates a new application instance)? Might help repro the original issue without the fix...

**Comment by mike183** [comment]
Refactored the test to avoid multiple calls to `this.visit`, but I still can't seem to reproduce the issue in the test suite...

**Comment by mike183** [comment]
So I managed to make a failing test for this 🎉

This should be ready for another review assuming CI is green once it finishes.

**Comment by rwjblue** [comment]
Thank you!!
