### PR TITLE
[BUGFIX] Regression [Ember 5.12+] Non helpful error when the function for on modifier was forgot as param

### LINKED ISSUE #20783: Non helpful error when the function for `on` modifier was forget to add
### 🐞 Describe the Bug
Beginning with ember v5.12 the error handing is not helpful when you forget to create the pass function to `on` modifier.

### 🔬 Minimal Reproduction
Create a `hbs` file with this content:

```hbs
<div {{on "click" this.myfunction}}></div>
```

Minimal reproduction: https://github.com/mkszepp/ember-missing-action-function

### 😕 Actual Behavior
If you forget to create the function in js/ts you will get this error:
Error in Firefox:
`Unhelpful error when there was not function passed to on modifier`
grafik

Error in Chrome:
```Uncaught TypeError: Cannot read properties of undefined (reading 'bind')```
grafik

### 🤔 Expected Behavior
We should bring back better error handling like it was in <= v5.11

```Uncaught Error: You must pass a function as the second argument to the `on` modifier; you passed undefined. While rendering:

this.myfunction```

grafik

### 🌍 Environment

- Ember: 5.12.0
- Ember-CLI: 5.12.0
- Node.js/pnpm: v20 / v9
- OS: Linux / WIndows
- Browser: Firefox / Chrome

### PR DESCRIPTION
**Pull request by johanrd**
Fixes #20783 / #21045                                                                                                                                                                                     
                                                                                                                                                                                                            
  Since Ember 5.12, passing a non-function to the `{{on}}` modifier produces an unhelpful `TypeError: Cannot read properties of undefined (reading 'bind') instead of the previous helpful message: "You must pass a function as the second argument to the on modifier; you passed undefined."`

### Root cause

The glimmer-vm refactor in https://github.com/glimmerjs/glimmer-vm/commit/2d9fc0174e5c49f0b79736664cd4162eccd4e6a8 replaced expect() (a runtime check that always executes) with localAssert() (guarded by LOCAL_DEBUG, which is stripped in published builds). This meant the callback validation became a no-op in published ember-source, while the .bind() call further down — guarded by DEBUG — still runs, producing the unhelpful TypeError.

The key distinction: LOCAL_DEBUG is only true when developing the ember.js repo itself. DEBUG (from @glimmer/env) is true in user app development mode. The existing test suite always runs with LOCAL_DEBUG=true, so this gap was never caught.

### Fix

  - Replace localAssert() with an explicit if (DEBUG) check, matching the pattern already used in the same function for positional argument validation
  - Add a smoke test that runs against built ember-source (LOCAL_DEBUG=false, DEBUG=true) — the exact environment users have — to prevent this class of regression

Cowritten by Claude.

Not sure whether it should be backported to LTS, considering the repo-merge.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Is the problem still present an canary?

Because: https://github.com/emberjs/ember.js/pull/21091

**Comment by johanrd** [comment]
@NullVoxPopuli yes, as I understand it, this needs to be tested in smoke tests to fully emulate the user dev mode?

 on `main`(canary), the smoke tests in this PR #21108 (which run with LOCAL_DEBUG=false, DEBUG=true, matching real user dev mode) confirm this. On main/canary:
```
  not ok 8 - on modifier | error handling: throws helpful error when callback is missing                                                                                                                                                      
      message: Expected helpful error message, got: Cannot read properties of undefined (reading 'bind')                                                                                                                                      
                                                                                                                                                                                                                                              
  not ok 9 - on modifier | error handling: throws helpful error when event name is missing                                                                                                                                                    
      message: Expected helpful error message, got: Cannot destructure property 'tag' of 'ref' as it is undefined.
```

PR #21091 improved error messages inside check() and localAssert(), but both are gated by LOCAL_DEBUG (not DEBUG), so they're no-ops in published builds. Users still get unhelpful TypeErrors. The fix in fix/20783 correctly replaces localAssert() with if (DEBUG) { throw ... }.

File: packages/@glimmer/runtime/lib/modifiers/on.ts [hunk 1]
```diff
@@ -57,13 +57,16 @@ export class OnModifierState {
...
-    );
+    let arg0 = args.positional[0];
+
+    if (DEBUG && !arg0) {
+      throw new Error(
+        'You must pass a valid DOM event name as the first argument to the `on` modifier'
+      );
+    }
 
     let eventName = check(
```
Comment (NullVoxPopuli) [inline packages/@glimmer/runtime/lib/modifiers/on.ts:72]: why not move eventName above the if statement here? so that way we aren't defining two variables that have the same value?

File: packages/@glimmer/runtime/lib/modifiers/on.ts [hunk 2]
```diff
@@ -57,13 +57,16 @@ export class OnModifierState {
   updateListener(): void {
     let { element, args, listener } = this;
 
-    localAssert(
-      args.positional[0],
-      'You must pass a valid DOM event name as the first argument to the `on` modifier'
-    );
+    let arg0 = args.positional[0];
+
+    if (DEBUG && !arg0) {
```
Comment (NullVoxPopuli) [inline packages/@glimmer/runtime/lib/modifiers/on.ts]: of note -- this type of error would make it to production, which I'm not sure is what we want -- is there anyway to do use `assert` from `@ember/debug`, perhaps?
We certainly want good errors for local  development.

or.. is there some similar utility on the glimmer side of things?


tho -- thinking more about this -- what sort of error occurs in production? is that the problem? production errors? or?

Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: I can at least verify that the issue in https://github.com/emberjs/ember.js/issues/20783 / https://github.com/emberjs/ember.js/issues/21045 :

```hbs
<div {{on "click" this.myfunction}}></div>
```
reproduces with `6.12.0-beta.1` which should include PR #21091

Comment (NullVoxPopuli) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: right, but what should happen in production?

File: packages/@glimmer/runtime/lib/modifiers/on.ts (hunk 1 above)
Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts:72]: thanks, pushed a fix

Comment (NullVoxPopuli) [reply packages/@glimmer/runtime/lib/modifiers/on.ts:72]: do we need arg0 now?

File: packages/@glimmer/runtime/lib/modifiers/on.ts (hunk 2 above)
Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: to my understanding:

In production, the behavior is unchanged from today: `if (DEBUG)` is stripped, `check()` is a no-op, so no validation runs. If someone somehow passes no callback in production, they'd get the same browser TypeError they get now. This fix only improves the dev experience. The problem is specifically the dev experience: `check()` and `localAssert()` are gated by `LOCAL_DEBUG`, not `DEBUG`. `LOCAL_DEBUG` is only `true` inside this repo's test suite — in user apps it's `false`, so those validations are no-ops. Users get `Cannot destructure property 'tag' of 'ref' as it is undefined` instead of the helpful message. The `if (DEBUG)` guard runs in user dev mode where `DEBUG=true`.

`if (DEBUG)` is stripped in production — same pattern as the other 5 `if (DEBUG)` blocks in this file. So no production overhead.

regarding `assert` from `@ember/debug` — `@glimmer/runtime` should perhaps not depend on @ember/debug, even after the repo merge? or? not sure.

File: packages/@glimmer/runtime/lib/modifiers/on.ts (hunk 1 above)
Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts:72]: args.positional[0] could be undefined, and valueForRef(undefined) would maybe crash runtime? 

We could inline it as `args.positional[0] ? valueForRef(args.positional[0]) : undefined`

Comment (NullVoxPopuli) [reply packages/@glimmer/runtime/lib/modifiers/on.ts:72]: naw, I mean like this:

```js
 let eventName = check(...)

if (DEBUG) {
  if (!eventName) { error stuff }
}

File: packages/@glimmer/runtime/lib/modifiers/on.ts (hunk 2 above)
Comment (NullVoxPopuli) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: sgtm -- and yea, let's leave the assert location alone for now -- problem for another time

File: packages/@glimmer/runtime/lib/modifiers/on.ts (hunk 1 above)
Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts:72]: okay, yes, unless I misunderstand, the rest of the file uses both patterns `if (DEBUG && condition)` on lines 67, 84, 92 and `if (DEBUG) { if (condition) }`on lines 102, 175. The arg0 is still needed and/or inlined in the ternary, right?

Comment (NullVoxPopuli) [reply packages/@glimmer/runtime/lib/modifiers/on.ts:72]: but arg0 === eventName?

(ignore if blocks -- they aren't important)

Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts:72]: isn't `args.positional[0]` a `Reference` object and eventName the resolved `string` (or `undefined`) from `valueForRef(args.positional[0])`?

Comment (NullVoxPopuli) [reply packages/@glimmer/runtime/lib/modifiers/on.ts:72]: ah you right -- I missed that 🙈

File: packages/@glimmer/runtime/lib/modifiers/on.ts [hunk 3]
```diff
@@ -57,13 +57,16 @@ export class OnModifierState {
...
+      throw new Error(
+        'You must pass a valid DOM event name as the first argument to the `on` modifier'
```
Comment (NullVoxPopuli) [inline packages/@glimmer/runtime/lib/modifiers/on.ts]: Should we say what was received instead? Can we provide even more information in the error? maybe the element tag name? (at least since it's kinda hard right now to find what element a modifier is on rn)

Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: yes, good idea.

Sentry reports something like `button.font-bold.hover:bg-white.focus-m-1[type="submit"]`

Even better would maybe be to use `element.cloneNode(false).outerHTML` which would print the whole node as in the dom, like `<button type="submit" class="font-bold hover:bg-white" id="save">`

It may be too long, but that may not be an issue?

Comment (NullVoxPopuli) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: how does sentry get that?

I do think it would b e too long to include the HTML

Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: heh, checked now, Sentry's `_htmlElementAsString` builds a compact CSS-selector-style representation: `button#save.btn.primary[type="submit"]`. See their implementation:  https://github.com/getsentry/sentry-javascript/blob/b3d336c98ee58f124004debf2e6aca60365d15b4/packages/core/src/utils/browser.ts#L68-L122                                                                                                    
                                                                                                                                                                                                                                              
It is quite complex, though. `element.cloneNode(false).outerHTML` is simpler and gives the full opening tag from the DOM, but it can get verbose with data attributes, analytics attributes etc. But is that an issue in dev mode? alternatively substring it.

Comment (NullVoxPopuli) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: how are they getting access to the element at all tho? 🤔

Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: this is part of the `breadcrumbsIntegration`, so it is always listening, i guess, then attaches the last trail when the error is caught.

They register a global click/keypress listener via `addClickKeypressInstrumentationHandler`. When a DOM event fires, they grab `event.target` and call `htmlTreeAsString(element)`

Comment (kategengler) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: Including html is questionable -- you don't want to leak any data from an app into an exception

Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: @kategengler ok, yes. something like this would be safe i guess:
```
You must pass a valid DOM event name as the first argument to the `on` modifier, 
but you passed undefined. Usage example: {{on "click" this.handleClick}}. (Element: <button>)
```

Adding the id and/or the class list would sometimes be helpful, but potentially leaking.

Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: pushed an update now with the tag name

Comment (kategengler) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: I think the classlist is probably fine. Sentry doesn't hide the classes.

**Review by NullVoxPopuli — DISMISSED** [review]

File: packages/@glimmer/runtime/lib/modifiers/on.ts (hunk 3 above)
Comment (johanrd) [reply packages/@glimmer/runtime/lib/modifiers/on.ts]: okay, added the id and class list now in css selector / sentry style: `button#save.btn.primary`

File: smoke-tests/scenarios/basic-test.ts [hunk 4]
```diff
@@ -223,6 +223,44 @@ function basicTest(scenarios: Scenarios, appName: string) {
 
               });
             `,
+            'on-modifier-error-test.gjs': `
```
Comment (NullVoxPopuli) [inline smoke-tests/scenarios/basic-test.ts:275]: one of these tests should probably include the selector text, ya?

Comment (johanrd) [reply smoke-tests/scenarios/basic-test.ts:275]: yes, good point, 
I added it as its own test now: https://github.com/emberjs/ember.js/pull/21108/changes/4bfdd86207e0ab9e4266cc98a91058bdb493d854

**Review by NullVoxPopuli — DISMISSED** [review]

**Comment by NullVoxPopuli** [comment]
@johanrd I forgot to merge this :( any chance you'd be willing to rebase, and one more time show the error message(s) before and after?

**Review by NullVoxPopuli — APPROVED** [review]

**Comment by johanrd** [comment]
@NullVoxPopuli Rebased now. See current CI for passing tests, and [here for failing tests without the fix](https://github.com/johanrd/ember.js/actions/runs/23605087288/job/68745889080?pr=12#step:5:68), e.g:



```
not ok 9 Chrome 145.0 - [36 ms] - on modifier | error handling: throws helpful error when callback is missing
        ---
            actual: >
                false
            expected: >
                true
            stack: >
                    at http://localhost:7357/assets/tests-DSd2Dm9s.js:10690:18
            message: >
                Expected helpful error message, got: Cannot read properties of undefined (reading 'bind')
            negative: >
                false
            browser log: |
        ...
    not ok 10 Chrome 145.0 - [52 ms] - on modifier | error handling: throws helpful error when event name is missing
        ---
            actual: >
                false
            expected: >
                true
            stack: >
                    at http://localhost:7357/assets/tests-DSd2Dm9s.js:10710:18
            message: >
                Expected helpful error message, got: Cannot destructure property 'tag' of 'ref' as it is undefined.
            negative: >
                false
            browser log: |
        ...
    not ok 11 Chrome 145.0 - [35 ms] - on modifier | error handling: error message includes element selector
        ---
            actual: >
                false
            expected: >
                true
            stack: >
                    at http://localhost:7357/assets/tests-DSd2Dm9s.js:10730:18
            message: >
                Expected element selector in error, got: Cannot read properties of undefined (reading 'bind')
            negative: >
                false
            browser log: |
        ...
```
