### PR TITLE
[BUGFIX canary] Decouple route transition from view creation

### LINKED ISSUE #9814: Tries to reuse a destroyed view when rerendering an outlet
1. Put this in application.hbs:

    ````handlebars
    {{input type="checkbox" checked=showOutlet}}
    {{#if showOutlet }}
      {{outlet}}
    {{/if}}
    ````
2. Put this in index.hbs:

    ``hello world``

3. Toggle the checkbox. The second time you toggle to true, Ember throws `Assertion Failed: calling set on destroyed object`. It looks to me like it's reusing a view that had already been destroyed on the previous render of the #if block.

This bug effects canary, both with and without HTMLBars. Under 1.8, the outlet fails to re-render, but it doesn't throw an exception.

### PR DESCRIPTION
**Pull request by ef4**
This closes #9814 and #10304, which are examples of a class of problems caused by
the way the router synchronously reaches into the view hierarchy to set
outlet state. It is a significant refactor of the way the router
communicates state to outlets.

What motivates this change?
- Simple examples like `{{#if something}}{{outlet}}{{/if}}` are
  incorrect under the current model.
- Richer examples like block-helpers to enable animation also
  suffer. In general, the router cannot know when and whether a
  particular outlet is going to exist, and it shouldn't need to know.
- The router maintains a bunch of view-related state that is actually
  redundant with the view hierarchy itself, leading to unnecessary
  complexity.
- This eliminates the longstanding weirdness & confusion caused by the
  fact that we used to create new `View` instances and then throw them
  away if they looked similar enough to ones that were already
  rendered. That functionality is now covered by state diffing in the
  `OutletView`.
- We reduce the API surface area between router and view layer in a way
  that should make it easier to experiment with swapping in compatible
  implementations of either.
- As a bonus, this changes makes outlets work in an observer-free way
  that will make them easy to integrate with upcoming planned view
  layer optimizations.

How does this work?
- Rather than directly building and linking views, the router builds up
  an abstract summary of the render decisions that have been made by
  the current routes.
- This state is cheap to recalculate as needed. It doesn't do any view
  creation. To avoid expensive observer creation & teardown, we just
  recreate the whole thing and use a `setState`-like mechanism to
  propagate the changes through the outlet hierarchy. This gives us
  optimal granularity of updates.
- Actual view instantiation moves into the OutletView -- within the
  view layer where it belongs. Each outlet does a diff to see whether
  it should rerender itself or propagate inner changes down to its
  child outlets.
- To bootstrap rendering, the router creates a single top-level outlet,
  after which all view creation is internal to the view layer.

Does this break any existing semantics?
- No, as far as I can tell.

Could this get even better if we decided to deprecate some old
semantics?
- Yes. It would be better if users' `renderTemplate` implementations on
  `Route`s were required to be idempotent. Then we could eliminate a
  bunch of the remaining state from them.
- Similarly, we should consider forbiding calling `render` and 
  `disconnectOutlet` at arbitrary times that are outside the scope of 
  `renderTemplate`. It makes the programming model harder to reason
  about.
- Also, when we deprecate the `render` helper we can eliminate the
  remaining use of `_activeViews` state tracking on the router. That is
  the only remaining use for it.

### CODE REVIEW

File: packages/ember-application/lib/system/application.js [hunk 1]
```diff
@@ -1003,6 +1004,7 @@ Application.reopenClass({
 
     registry.injection('view', 'renderer', 'renderer:-dom');
     registry.register('view:select', SelectView);
+    registry.register('view:outlet', OutletView);
```
Comment (rwjblue) [inline packages/ember-application/lib/system/application.js]: I think this should be prefixed with a dash, it is private and we don't want any apps having collisions with their `outlet` routes...

**Comment by rwjblue** [comment]
This looks wonderful!

File: packages/ember-application/lib/system/application.js (hunk 1 above)
Comment (ef4) [inline packages/ember-application/lib/system/application.js]: I have no strong feelings about this, but why is it different from all these other registrations that are not prefixed? They all seem equally subject to collisions.

Comment (ef4) [inline packages/ember-application/lib/system/application.js]: I guess because we consider the others public API that people are supposed to know about. Hmm.

Comment (stefanpenner) [inline packages/ember-application/lib/system/application.js]: I am unsure if the others are public api either. But regardless this offers a mild buffer from resolved alternatives.

**Comment by quaertym** [comment]
:+1:

File: packages/ember-application/lib/system/application.js (hunk 1 above)
Comment (rwjblue) [inline packages/ember-application/lib/system/application.js]: My concern is that adding this here removes the ability for apps to use the word "outlet" as a route name.

As far as why the others are not prefixed, I only see three other views being registered:

* `select` was added intentionally as public API (to be used as `{{view 'select'}}`), and was therefore not prefixed.
* `view:toplevel` and `view:default` have existed since v1.0.0-rc1 (see [here](https://github.com/emberjs/ember.js/blob/v1.0.0-rc.1/packages/ember-routing/lib/system/router.js#L59-60)).  I am unsure if it is considered public API, but it is grandfathered in under SemVer (as far as naming collisions go) due to being present pre-1.0.0.

**Comment by jcope2013** [comment]
:+1:

File: packages/ember-application/lib/system/application.js (hunk 1 above)
Comment (rwjblue) [inline packages/ember-application/lib/system/application.js]: If your position is that this is actually a public API (for example if folks are supposed to put a file at `app/views/outlet.js` that exports a custom OutletView), I suppose that is a different argument, but I do not think that is what you are suggesting...

Comment (ef4) [inline packages/ember-application/lib/system/application.js]: Nah, that's fine, I will add the dash.

**Comment by ef4** [comment]
@rwjblue has pointed out that this will let us remove the `isTop` flag that gets added by the template compiler.

And @mmun pointed out that this eliminates our last internal use of ContainerView's `currentView`, giving us the option of deprecating it.

**Comment by mmun** [comment]
:clap:

**Comment by rwjblue** [comment]
I accidentally branched for the 1.11 betas before this landed.  Pulled in for 1.11.0-beta.2.

File: packages/ember-routing/lib/system/router.js [hunk 2]
```diff
@@ -949,4 +992,45 @@ function forEachQueryParam(router, targetRouteName, queryParams, callback) {
...
+    }
+  }
+}
+
+function appendLiveRoute(liveRoutes, route, parentRoute, defaultParentState, renderOptions) {
+  var targetName;
+  var target;
+  var myState = {
+    render: renderOptions,
+    outlets: Object.create(null)
```
Comment (machty) [inline packages/ember-routing/lib/system/router.js]: I believe this needs to be `Ember.create` for ie8 et al support

**Comment by tim-evans** [comment]
I'm using canary, and it seems like this refactoring broke my app.

```javascript
this.connections.push(renderOptions);
```

`this.connections` is `undefined`. Are there other deprecations that come with this change that should be communicated?

**Comment by rwjblue** [comment]
@tim-evans - Can you open an issue with a repro so we can track this down?

**Comment by tim-evans** [comment]
@rwjblue I'll try to do this, but I'm currently in a big upgrade from 1.8 to 1.11. I'm just flagging this as an issue for now.

**Comment by rwjblue** [comment]
@tim-evans - Gotcha, good luck!

**Comment by machty** [comment]
@tim-evans I'd be on the lookout for a `this.render()` in an unusual place (e.g. outside of renderTemplate or action handlers), but I could be wrong.

**Comment by tim-evans** [comment]
@machty just checked around that, but it doesn't seem to be it at first glance.

File: packages/ember-routing/lib/system/router.js (hunk 2 above)
Comment (stefanpenner) [inline packages/ember-routing/lib/system/router.js]: ya cc @ef4

Comment (rwjblue) [inline packages/ember-routing/lib/system/router.js]: @stefanpenner - It was already fixed in a followup PR.

Comment (stefanpenner) [inline packages/ember-routing/lib/system/router.js]: :+1:

**Comment by kamal** [comment]
One use case that broke for me is calling `this.render` without specifying the `into` option. Somehow Ember used to be able to look up the chain of templates to find the first named outlet?

This used to work:
```javascript
renderTemplate: function(){
  this._super();
  this.render('settings/_nav', {
    outlet: 'subnav'
  });
}

**Comment by mixonic** [comment]
@kamal that sounds like a regression. I suggest opening a ticket (ideally with a reproduction) to track a fix.
