### PR TITLE
[Bugfix release] allow class-based helpers to work in strict-mode

### LINKED ISSUE #19877: [Bug] class-based helpers throw weird error in strict mode (getDebugName)
### 🐞 Describe the Bug
Error wasn't expected, but I think phrasing of the error could be improved?

image

### 🔬 Minimal Reproduction

1. define class based helper in my-app/helpers
2. using ember-template-imports (or strict mode some other way), define this template:
  ```js
  import MyHelper from 'my-app/helpers/my-helper';
  
  <template>
    {{#let (MyHelper 1 2) as |result|}}
      {{result}}
    {{/let}}
  </template>
  ```

### 😕 Actual Behavior
image

actual helper is:
```js
import { getOwner } from '@ember/application';
import Helper from '@ember/component/helper';

export default class GetService extends Helper {
  compute([name]: [string]) {
    return getOwner(this).lookup(`service:${name}`);
  }
}
```

### 🤔 Expected Behavior
primarily, I expected this to work:
```js
import service from 'limber/helpers/service';

<template>
  {{#let (service 'editor') as |context|}}
```
but a more helpful error would have been preferable, given the situation?

### 🌍 Environment

- Ember: - 4.0.1
- Node.js/npm: - 16.13.0 / 8.1.3 / yarn 1.22.17
- OS: - Ubuntu 21.10
- Browser: - FireFox

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Resolves https://github.com/emberjs/ember.js/issues/19877

### CODE REVIEW

File: smoke-tests/ember-test-app/tests/integration/strict-mode-test.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+import { setupRenderingTest } from 'ember-qunit';
+import { render } from '@ember/test-helpers';
+import { precompileTemplate } from '@ember/template-compilation';
+
+import service from 'ember-test-app/helpers/service';
+
+module('tests/integration/components/gjs', function (hooks) {
+  setupRenderingTest(hooks);
+
+  test('it works with ember helpers', async function (assert) {
```
Comment (NullVoxPopuli) [inline smoke-tests/ember-test-app/tests/integration/strict-mode-test.js:11]: I added a whole app for just this tset because I couldn't find any other place where I'd have access to all the thing that this test requires.

If such a place exists, I'm happy to move this test there.
I think having a full app though to make sure things are roughly still wired up ok is good

File: packages/@ember/-internals/glimmer/lib/helper.ts [hunk 2]
```diff
@@ -179,7 +179,7 @@ class ClassicHelperManager implements HelperManager<ClassicHelperStateBucket> {
   }
 
   getDebugName(definition: ClassHelperFactory) {
-    return getDebugName!(definition.class!['prototype']);
+    return getDebugName!((definition.class || definition)!['prototype']);
```
Comment (NullVoxPopuli) [inline packages/@ember/-internals/glimmer/lib/helper.ts:182]: when a class-based helper is used in strict mode, there is no class property

**Comment by patricklx** [comment]
might this be related? https://github.com/emberjs/ember.js/issues/19518

**Comment by NullVoxPopuli** [comment]
@patricklx I think it might be!! yeah!

**Comment by mixonic** [comment]
This fix is probably ok, but I would like it tested in the existing test harness and not an entirely new suite. Adding a whole new kind of smoke test should a) be decoupled into its own PR and b) does not preclude ensuring regressions have coverage added in the internal non-smoke test suite.

That is the main blocker I see here. Is this a bugfix-release? Bugfix-lts?

**Comment by NullVoxPopuli** [comment]
> Is this a bugfix-release? Bugfix-lts?

It's a bug on 4.0+, afaict (I haven't checked earlier) -- so, bugfix-release?

>  but I would like it tested in the existing test harness

where would a test like this go?

> a) be decoupled into its own PR

can do!

**Comment by NullVoxPopuli** [comment]
I'm having issues with the test. any help is much appreciated <3

**Comment by kategengler** [comment]
Merging on approvals from #19884
