### PR TITLE
[BUGFIX beta] Change error message when Ember.computed.and/or contain…

### LINKED ISSUE #13176: Confusing error when using `Ember.computed.or` incorrectly
I wasn't thinking very hard, and tried to do:
`Ember.computed.or('someKey', 'tried to put a default string here')`
The error that popped up didn't really inform me what was going on:
> Error: Brace expanded properties cannot contain spaces, e.g. 'user.{firstName, lastName}' should be 'user.{firstName,lastName}'

More helpful would have been an assertion error, something like
> Assertion Failed: Dependent keys passed to Ember.computed.or() can't have spaces

### PR DESCRIPTION
**Pull request by chena**
Fixes #13176

### CODE REVIEW

**Comment by courajs** [comment]
Hey @rwjblue, how's this look?

File: packages/ember-runtime/lib/computed/computed_macros.js [hunk 1]
```diff
@@ -20,7 +20,10 @@ function expandPropertiesToArray(properties) {
   }
 
   for (let i = 0; i < properties.length; i++) {
-    expandProperties(properties[i], extractProperty);
+    let property = properties[i];
+    assert('Dependent keys passed to Ember.computed.and() or Ember.computed.or() can\'t have spaces.', property.indexOf(' ') < 0);
```
Comment (rwjblue) [inline packages/ember-runtime/lib/computed/computed_macros.js]: Looks good, but I'd much prefer the message to be tailored to the specific type of computer macro that was being used. Is this same message fired for ither macros? If it is, can we somehow pass in the macro being used and use that in the message directly?

Comment (chena) [inline packages/ember-runtime/lib/computed/computed_macros.js]: @rwjblue @courajs I wonder if the only way to  know which macro is being processed is to pass it along explicitly (ie. "and" or "or"), since the predicate from the caller `generateComputedWithPredicate` is a callback that can be arbitrary?

Comment (rwjblue) [inline packages/ember-runtime/lib/computed/computed_macros.js]: Ya, that was what I was worried about. How hard would it be do do that?

Comment (courajs) [inline packages/ember-runtime/lib/computed/computed_macros.js]: Adding a second argument `label` to `generateComputedWithPredicate` and `expandPropertiesToArray` should work out well. It seemed a little awkward to me at first, but it leads to better messages for the user. If they've used both `and` and `or` in their app, this will help them narrow it down.

**Comment by courajs** [comment]
LGTM!

**Comment by stefanpenner** [comment]
👍

**Comment by courajs** [comment]
Congrats @chena on first PR! Thanks :)
