### PR TITLE
[BUGFIX] Using query params helper outside of link-to

### LINKED ISSUE #18076: [Regression] [v3.10] The `(query-params)` helper can only be used when invoking the `{{link-to}}` component.
The PR #17779 introduced a backwards-incompatible change in v3.10, which should not have made it into the framework until v4.0 with deprecation warnings preceding its removal.

For many versions of Ember I've been able to do the following, but since this PR landed and v3.10 shipped, I now am presented with an error: <code>The `(query-params)` helper can only be used when invoking the `{{link-to}}` component.</code>

```hbs
{{!-- app/templates/index.hbs --}}
{{my-component optional-params=(if foo (query-params bar="baz"))}}
```

```hbs
{{!-- my-component.hbs --}}
{{#if optional-params}}
  {{#link-to "my.route" optional-params class="actionable"}}Schedule{{/link-to}}
{{else}}
  {{#link-to "my.route" class="passive"}}View{{/link-to}}
{{/if}}
```

This breaks our production application. This should be considered a breaking change. Its presence in v3.10.0 and v3.10.1 should be considered a regression, and I'd love to see a patch version v3.10.2.

### PR DESCRIPTION
**Pull request by Alonski**
The (query-params) helper has always been able to be used outside of `link-to`.
This PR broke it: #17779 

Fixes: #18076 

Recommendations:
This should be backported to the version in which #17779 was included.

Thanks a lot to @rwjblue for the help in fixing this 😄

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]

File: packages/@ember/-internals/glimmer/lib/components/link-to.ts [hunk 1]
```diff
@@ -838,14 +838,14 @@ const LinkComponent = EmberComponent.extend({
...
-      if (DEBUG && this.query === UNDEFINED) {
-        let { _models: models } = this;
-        let lastModel = models.length > 0 && models[models.length - 1];
-
-        assert(
-          'The `(query-params)` helper can only be used when invoking the `{{link-to}}` component.',
-          !(lastModel && lastModel.isQueryParams)
-        );
+      let { _models: models } = this;
+      if (models.length > 0) {
```
Comment (chancancode) [inline packages/@ember/-internals/glimmer/lib/components/link-to.ts]: I think we need to keep this.query === UNDEFINED (and maybe assert you can’t have both)

**Review by chancancode — CHANGES_REQUESTED** [review]

File: packages/@ember/-internals/glimmer/lib/components/link-to.ts (hunk 1 above)
Comment (Alonski) [reply packages/@ember/-internals/glimmer/lib/components/link-to.ts]: @chancancode Can you please help me understand exactly what you mean? What should the code be?

Comment (chancancode) [reply packages/@ember/-internals/glimmer/lib/components/link-to.ts]:
```js
if (this.query === UNDEFINED) {
  let { _models: models } = this;

  if (models.length > 0) {
    let maybeQueryParams = models[models.length - 1];

    if (isQueryParams(maybeQueryParams)) {
      this.query = maybeQueryParams.values;
      models.pop();
    }
  }
} else {
  assert('Cannot pass a QueryParams object in @models and @query at the same time', this.models.length === 0 || isQueryParams(this.models[this.models.length - 1]));
}
```

```ts
// packages/@ember/-internals/routing/lib/system/query_params.ts

import { Option } from '@glimmer/interfaces';

export default class QueryParams {
  readonly values: Option<object>;
  readonly isQueryParams = true;

  constructor(readonly values: Option< object> = null) {
  }
}

export function isQueryParams(obj: unknown): obj is QueryParams {
  return typeof obj === 'object' && obj !== null && obj['isQueryParams'] === true;
}
```

Comment (chancancode) [reply packages/@ember/-internals/glimmer/lib/components/link-to.ts]: I actually don't know why the `QueryParams` constructor accepts `null` here, is that a public API?

Comment (rwjblue) [reply packages/@ember/-internals/glimmer/lib/components/link-to.ts]: @chancancode - In general, I agree that you shouldn't be able to set both `@query` and pass a `(query-param` as the last model, however I don't think we can check `this.query === UNDEFINED` unless we also change where we save off the query param value. Given the snippet you suggested above, we would only update `this.query` the first time (not for each subsequent `didReceiveAttrs` where we could have a completely new value).

Comment (Alonski) [reply packages/@ember/-internals/glimmer/lib/components/link-to.ts]: @chancancode I don't understand the `query_params.ts` snippet.
This will change the behavior of the class. Why is values not a property anymore?

**Comment by Alonski** [comment]
@chancancode I push some more code. Is this what you wanted?
I had to negate the assertion to get tests passing

**Comment by Alonski** [comment]
CI Failure seems like a false negative

File: packages/@ember/-internals/glimmer/lib/components/link-to.ts (hunk 1 above)
Comment (chancancode) [reply packages/@ember/-internals/glimmer/lib/components/link-to.ts]: Okay sorry I think I understand the problem now. I know how to fix it but I'll do it later. You can revert to what you had before here (removing the `this.query === UNDEFINED` check and the assertion I added).

Comment (chancancode) [reply packages/@ember/-internals/glimmer/lib/components/link-to.ts]: @Alonski in TypeScript, `constructor(readonly values: Option<object> = null)` is a shorthand for declaring the field and assigning it from the constructor:

```ts
export default class QueryParams {
  constructor(readonly values: Option< object> = null) {
  }

  get isQueryParams(): true {
    return true;
  }
}
```

...is the same as...

```ts
export default class QueryParams {
  readonly values: Option<object>;

  constructor(values: Option< object> = null) {
    this.values = values;
  }

  get isQueryParams(): true {
    return true;
  }
}
```

File: packages/@ember/-internals/glimmer/lib/components/link-to.ts [hunk 2]
```diff
@@ -838,13 +839,20 @@ const LinkComponent = EmberComponent.extend({
...
       );
 
-      if (DEBUG && this.query === UNDEFINED) {
+      if (this.query === UNDEFINED) {
         let { _models: models } = this;
-        let lastModel = models.length > 0 && models[models.length - 1];
+        if (models.length > 0) {
+          let lastModel = models[models.length - 1];
 
+          if (typeof lastModel === 'object' && lastModel !== null && lastModel.isQueryParams) {
```
Comment (chancancode) [inline packages/@ember/-internals/glimmer/lib/components/link-to.ts]:
```suggestion
          if (isQueryParams(lastModel)) {
```

**Comment by Alonski** [comment]
@chancancode Reverted commit

**Comment by NullVoxPopuli** [comment]
This is exciting! Once this is merged & back ported, I can start upgrading a bunch of things to 3.12 from 3.8 :)

**Comment by chancancode** [comment]
Oops, I should have used squash and merge. Oh well.

**Comment by chancancode** [comment]
Backported to beta and release, I think we usually hold off on LTS backports until the stable release  has been cut.

**Comment by Alonski** [comment]
Thanks! So this will be backported after 3.14 or 3.15 is released?

**Comment by Alonski** [comment]
@chancancode Any idea when this will be backported to 3.12?
