### PR TITLE
Merge pull request #18707 from emberjs/bugfix/fix-object-proxy-tags

### LINKED ISSUE #18704: [3.13+] ObjectProxy not rerendering
Original report:

We're experienceing an almost identical issue when bumping an app from 3.12 to 3.13.

We have a utility function which returns a CP which returns an ObjectProxy which proxies the object passed to the utility (e.g. myUtil('model')). We've been using this primarily to store updates to form values locally.
```js
let myUtil = function (contentKey) {
  return computed(
    contentKey,
    function () {
      return MyProxyObject.create({ content: this.get(contentKey) });
    }
  );
}
```

We have a unit test (this is very abbreviated): 
```js
let foo = { bar: false };
let myController = Controller.extend({
  wrappedFoo: myUtil('foo'),
  computedBar: computed(
    'wrappedFoo.bar',
    function () { return this.get('wrappedFoo.bar'); }
  ),
  booledBar: bool('wrappedFoo.bar')
}).create({ foo });

assert.notOk(myController.get('aliasedBar'));
myController.set('wrappedFoo.bar', true);
assert.ok(myController.get('computedBar')); // was passing, now failing
assert.ok(myController.get('booledBar')); // was passing, now failing
```

cc @theroncross, [Original context](https://github.com/emberjs/ember.js/issues/18689#issuecomment-577294423)

I'm currently unable to reproduce this issue, with the following test case added to Ember directly:

```js
    '@test it should work when returned from a computed property'(assert) {
      function myUtil(contentKey) {
        return computed(contentKey, function() {
          return ObjectProxy.create({ content: this.get(contentKey) });
        });
      }

      let foo = { bar: false };
      let myController = EmberObject.extend({
        wrappedFoo: myUtil('foo'),
        computedBar: computed('wrappedFoo.bar', function() {
          return this.get('wrappedFoo.bar');
        }),
        booledBar: bool('wrappedFoo.bar'),
      }).create({ foo });

      assert.notOk(myController.get('aliasedBar'));
      myController.set('wrappedFoo.bar', true);
      assert.ok(myController.get('computedBar'));
      assert.ok(myController.get('booledBar'));
    }
```

### PR DESCRIPTION
**Pull request by pzuraq**
Currently, the Proxy mixin uses the private `UNKNOWN_PROPERTY_TAG` API
to provide the tags for the content property that the mixin is proxying
to. However, previously the chains system would do this _and_ still
entangle changes to the local property. This allowed users to manually
notify in subclasses of Proxy.

This PR adds the tag for the property back to the returned tag, so it
works the same as before. It also refactors `setupMandatorySetter`,
since we now have to do that work in two places (to avoid re-entry).

Fixes #18704

### CODE REVIEW

File: packages/@ember/-internals/runtime/lib/mixins/-proxy.js [hunk 1]
```diff
@@ -58,7 +59,16 @@ export default Mixin.create({
   }),
 
   [UNKNOWN_PROPERTY_TAG](key) {
-    return combine(getChainTagsForKey(this, `content.${key}`));
+    let tag = tagFor(this, key);
+
+    if (DEBUG) {
+      setupMandatorySetter(tag, this, key);
```
Comment (rwjblue) [inline packages/@ember/-internals/runtime/lib/mixins/-proxy.js]: Doesn't this mean that we automatically define each of these keys on the proxy instance? E.g. `Object.keys` output would be changed.

That seems a bit wrong, no?

**Review by rwjblue — CHANGES_REQUESTED** [review]

File: packages/@ember/-internals/runtime/lib/mixins/-proxy.js (hunk 1 above)
Comment (pzuraq) [reply packages/@ember/-internals/runtime/lib/mixins/-proxy.js]: It does, my mistake there. We should likely have a test for this.

**Review by rwjblue — APPROVED** [review]

**Comment by theroncross** [comment]
Any chance this will make it back to 3.13?

**Comment by pzuraq** [comment]
This will be backported to 3.16, since it is an LTS. We do not support 3.13 anymore.
