### PR TITLE
[BUGFIX] Track applicationInstances created by Ember.Application for teardown

### LINKED ISSUE #15327: Error during initial render causes non-globals `Application` visit promise to hang
Preamble:

`Ember.Application` has a globals a non-globals mode. This has nothing to do with the resolver. Instead, it refers to applications which have been autobooted. Amongst other impacts of being globals, these applications set a `MyApp.__deprecatedInstance__` that implies only a single `applicationInstance` is running for a given app.

---

Given a test like the following:

```js
import {
  moduleFor,
  ApplicationTestCase,
  AutobootApplicationTestCase
} from 'internal-test-helpers';

moduleFor('The {{link-to}} helper', class extends ApplicationTestCase {
  [`@test the {{link-to}} helper throws a useful error if you invoke it wrong`](assert) {
    this.router.map(function() {
      this.route('post', { path: 'post/:post_id' });
    });
    this.addTemplate('application', `{{#link-to 'post'}}Post{{/link-to}}`);

    assert.throws(() => {
      this.visit('/');
    }, /(You attempted to define a `\{\{link-to "post"\}\}` but did not pass the parameters required for generating its dynamic segments.|You must provide param `post_id` to `generate`)/);
  }
});
```

All following tests will fail with errors like:

* `Assertion Failed: You cannot use the same root element (DIV) multiple times in an Ember.Application`
* `Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction`

This is because the application instance created during the `visit` call is never destroyed. The way destruction is supposed to happen is simple: The `AbstractApplicationTestCase` [sets `this.applicationInstance` on the test context](https://github.com/emberjs/ember.js/blob/d338c608e5ce00eb98d2617f4b2e7d102035b6e4/packages/internal-test-helpers/lib/test-cases/abstract-application.js#L63) after a successful transition. At [teardown the instance is destroyed](https://github.com/emberjs/ember.js/blob/d338c608e5ce00eb98d2617f4b2e7d102035b6e4/packages/internal-test-helpers/lib/test-cases/abstract-application.js#L52). If the initial transition fails (say an exception raised from the model hook) then there is no `applicationInstance`.

In theory this is just fine, when a transition fails [`Application.visit` already takes care of destroying the instance](https://github.com/emberjs/ember.js/blob/d338c608e5ce00eb98d2617f4b2e7d102035b6e4/packages/ember-application/lib/system/application.js#L978). The test harness should only need to know about success cases.

However, **exceptions during rendering do not cause an initial `visit` promise to fail**. `ApplicationInstance` [schedules the resolution of its own visit promise into `afterRender`](https://github.com/emberjs/ember.js/blob/d338c608e5ce00eb98d2617f4b2e7d102035b6e4/packages/ember-application/lib/system/application-instance.js#L257). An exception during rendering means `afterRender` doesn't run, and so that promise just hangs. The instance destruction code in `Application` never gets run.

Why doesn't this happen to globals mode apps? Globals mode apps [set the `__deprecatedInstance__` property before render](https://github.com/emberjs/ember.js/blob/d338c608e5ce00eb98d2617f4b2e7d102035b6e4/packages/ember-application/lib/system/application.js#L417). When a globals mode `Application` is destroyed, [it uses that property to destroy the `applicationInstance`](https://github.com/emberjs/ember.js/blob/d338c608e5ce00eb98d2617f4b2e7d102035b6e4/packages/ember-application/lib/system/application.js#L770). Because non-globals applications don't set this property or have a similar instance-tracking system, they fail to destroy `applicationInstance` when `destroy` is called on the application itself.

I propose that `Application` should track `ApplicationInstance` instances it creates in an array and upon its own destruction destroy each of them. That would permit applications that fail their initial rendering pass to be property torn down.

References https://github.com/emberjs/ember.js/pull/15319. Discovered this porting a test to the harness.

### PR DESCRIPTION
**Pull request by kpfefferle**
Resolves #15327 

The fixes here occur within `packages/ember-application/lib/system/application.js`:
- Add a private/internal `_applicationInstances` array property to `Ember.Application`
- Push each `applicationInstance` onto the `_applicationInstances` array each time one is created with `buildInstance()`
- Splice an `applicationInstance` out of the `_applicationInstances` array if it is destroyed so that we're not leaking instances after they have been destroyed
- During `willDestroy()`, check for the length of `_applicationInstances` and call `destroy()` on each one to make sure we are tearing down all `applicationInstances`

I have also refactored a couple of tests that were using Ember globals mode to work around the bug described in #15327. There are still a couple of tests that need to be refactored (noted below).

TODO:
- [x] Refactor [component_registration_test](https://github.com/emberjs/ember.js/blob/98cc07f7efeeabed7524511966a510e0470b1000/packages/ember/tests/component_registration_test.js#L170-L197) to not use globals mode workaround ~~_(note that this *entire* test file is using Ember's globals mode, so I'm unsure if the entire file needs refactored or if the note simply needs removed from this one test)_~~
- [x] Refactor [substates_test](https://github.com/emberjs/ember.js/blob/7dd709422e1961dffe65a967fc48b0e5940a0200/packages/ember/tests/routing/substates_test.js#L441-L502) to not use globals mode workaround
- [x] Add unit tests to `Ember.Application`:
  - [x] Test that each applicationInstance created by `buildInstance()` gets added to `_applicationInstances`
  - [x] Test that a destroyed applicationInstance gets spliced out of `_applicationInstances`
  - [x] Test that `willDestroy()` calls `destroy()` on each applicationInstance that has been added to `_applicationInstances`

cc: @mixonic

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
As it stands, this leaks `ApplicationInstance` instances in things like fastboot and non `packages/ember-testing` related tests. In those circumstances many `ApplicationInstance` instances are created and "thrown away" to be garbage collected.

I think an alternative way to solve the same general problem would be to have the `ApplicationInstance` push itself into the `Application`'s `_applicationInstances ` array, then splice itself out of that array in the `ApplicationInstance#willDestroy`.  This setup would avoid leaking the `ApplicationInstance` when things are handled properly (e.g. in non-error conditions) and still provide the cleanup that is needed when things go haywire in a given test...

File: packages/ember-application/lib/system/application.js [hunk 1]
```diff
@@ -762,6 +776,10 @@ const Application = Engine.extend({
       _loaded.application = undefined;
     }
 
+    if (this._applicationInstances.length) {
+      this._applicationInstances.forEach(i => i.destroy());
```
Comment (rwjblue) [inline packages/ember-application/lib/system/application.js]: Should reset the array after looping through and destroying, thinking `this._applicaitonInstances.length = 0` or something...

File: packages/ember-application/lib/system/application.js [hunk 2]
```diff
@@ -762,6 +776,10 @@ const Application = Engine.extend({
...
+    }
+
     if (this._globalsMode && this.__deprecatedInstance__) {
```
Comment (rwjblue) [inline packages/ember-application/lib/system/application.js]: Seems like this might be able to be removed now? `this.__deprecatedInstance__` is assigned to the result of calling `this.buildInstance()`, so the `this.__deprecatedInstance__` would already have been destroyed by the loop above...

**Review by rwjblue — COMMENTED** [review]
The test cleanup here is looking really nice! Please keep it up!

Still have the same concerns as mentioned previously about leakage. As of https://github.com/emberjs/ember-test-helpers/pull/237 (which is included in `ember-cli@2.17.0` out of the box) we create a single application instance and call `application.buildInstance()` once for each test in the application (and subsequently destroy them during normal test teardown). The array created to track all created `Ember.ApplicationInstance` instances **will** leak the entire contents of the container for each test (the same leak will occur in fastboot per request).

The simple fix (as mentioned above) is to have the `ApplicationInstance` instances splice their own entry out of the array (possibly by adding a `Ember.Application.prototype.destroyInstance` which would be the inverse of `Ember.Application.prototype.buildInstance`).

**Comment by rwjblue** [comment]
Ping?

**Comment by kpfefferle** [comment]
@rwjblue I made some solid progress on this over the break. I should be able to push up a review-ready update by the end of the week.

**Comment by krisselden** [comment]
@kpfefferle this is blocking me at the moment, I need to wrap up this PR, so if you want me to base it off this PR or your solid WIP please push your latest.

**Comment by krisselden** [comment]
@rwjblue should this target [BUGFIX beta]?

**Comment by kpfefferle** [comment]
@krisselden @rwjblue I believe that this is ready for final review now. If you need me to target a different branch (or anything else), let me know and I will take care of it tomorrow.

File: packages/ember/tests/component_registration_test.js [hunk 3]
```diff
@@ -1,162 +1,177 @@
...
+      initialize(applicationInstance) {
+        applicationInstance.register('component:expand-it', Component.extend({
+          classNames: 'testing123'
+        }));
+      }
     });
 
-    let text = this.$('div.testing123').text().trim();
-    assert.equal(text, 'hello world', 'The component is composed correctly');
+    this.visit('/').then(() => {
```
Comment (rwjblue) [inline packages/ember/tests/component_registration_test.js]: Needs a return

File: packages/ember/tests/component_registration_test.js [hunk 4]
```diff
@@ -1,162 +1,177 @@
...
+    this.application.instanceInitializer({
+      name: 'borf-snorlax-component-template',
+      initialize(applicationInstance) {
+        applicationInstance.register('template:components/borf-snorlax', compile('goodfreakingTIMES{{yield}}'));
+      }
     });
 
-    let text = this.$('#wrapper').text().trim();
-    assert.equal(text, 'hello world goodfreakingTIMES-goodfreakingTIMES!!!', 'The component is composed correctly');
+    this.visit('/').then(() => {
```
Comment (rwjblue) [inline packages/ember/tests/component_registration_test.js]: return

File: packages/ember/tests/component_registration_test.js [hunk 5]
```diff
@@ -1,162 +1,177 @@
...
+        applicationInstance.register('component:my-component', Component.extend({
+          text: 'inner',
+          layoutName: 'foo-bar-baz'
+        }));
+      }
     });
 
-    let text = this.$('#wrapper').text().trim();
-    assert.equal(text, 'inner-outer', 'The component is composed correctly');
+    this.visit('/').then(() => {
```
Comment (rwjblue) [inline packages/ember/tests/component_registration_test.js]: return

File: packages/ember/tests/component_registration_test.js [hunk 6]
```diff
@@ -1,162 +1,177 @@
...
+          text: 'inner',
+          layoutName: 'foo-bar-baz',
+          layout: compile('{{text}}-{{yield}}')
+        }));
+      }
     });
 
-    let text = this.$('#wrapper').text().trim();
-    assert.equal(text, 'inner-outer', 'The component is composed correctly');
+    this.visit('/').then(() => {
```
Comment (rwjblue) [inline packages/ember/tests/component_registration_test.js]: return

File: packages/ember/tests/component_registration_test.js [hunk 7]
```diff
@@ -1,162 +1,177 @@
...
   ['@test Using name of component that does not exist']() {
-    expectAssertion(() => {
-      this.runTask(() => {
-        this.createApplication();
+    this.addTemplate('application', `<div id='wrapper'>{{#no-good}} {{/no-good}}</div>`);
 
-        this.addTemplate('application', `<div id='wrapper'>{{#no-good}} {{/no-good}}</div>`);
-      });
+    expectAssertion(() => {
+      this.visit('/');
```
Comment (rwjblue) [inline packages/ember/tests/component_registration_test.js]: I don't know exactly how to handle this case properly. Currently `expectAssertion` doesnt' deal with async, the prior `runTask` wrapping was forcing it to be "pseudo-sync"

File: packages/ember/tests/routing/substates_test.js [hunk 8]
```diff
@@ -436,64 +433,41 @@ moduleFor('Loading/Error Substates', class extends ApplicationTestCase {
...
+      <p id="toplevel-error">TOPLEVEL ERROR: {{model.msg}}</p>
+    `);
 
-    let text = this.$('#toplevel-error').text();
-    assert.equal(
-      text,
-      'TOPLEVEL ERROR: BAD NEWS BEARS',
-      'toplevel error rendered'
-    );
+    this.visit('/').then(() => {
```
Comment (rwjblue) [inline packages/ember/tests/routing/substates_test.js]: return

File: packages/ember/tests/routing/substates_test.js [hunk 9]
```diff
@@ -436,64 +433,41 @@ moduleFor('Loading/Error Substates', class extends ApplicationTestCase {
...
+        text,
+        'TOPLEVEL ERROR: BAD NEWS BEARS',
+        'toplevel error rendered'
+      );
+    });
 
     reject = false;
 
-    return this.visit('/').then(() => {
+    this.visit('/').then(() => {
```
Comment (rwjblue) [inline packages/ember/tests/routing/substates_test.js]: return

File: packages/ember/tests/component_registration_test.js (hunk 7 above)
Comment (kpfefferle) [reply packages/ember/tests/component_registration_test.js]: Would something like this work?
```js
expectAssertion(() => {
  this.runTask(() => this.visit('/'));
}, /.* named "no-good" .*/);
```
The test passes either way, so I'm not sure what the proper refactor here is.

**Comment by mixonic** [comment]
@kpfefferle can you squash into a single commit and prefix the commit message with `[BUGFIX beta]` please? It can still target `master`.

File: packages/ember/tests/component_registration_test.js (hunk 7 above)
Comment (rwjblue) [reply packages/ember/tests/component_registration_test.js]: The test passes either way because `this.visit` is sync at the moment 😭 .

@mixonic reminded me that `expectAssertion(/some regexp/)` can be used to handle the async cases like this, maybe we could swap to that instead?

File: packages/ember-application/lib/system/application.js [hunk 10]
```diff
@@ -368,7 +380,23 @@ const Application = Engine.extend({
   buildInstance(options = {}) {
     options.base = this;
     options.application = this;
-    return ApplicationInstance.create(options);
+    let instance = ApplicationInstance.create(options);
+    this._applicationInstances.push(instance);
```
Comment (rwjblue) [inline packages/ember-application/lib/system/application.js]: I would vaguely prefer to have this done by the `ApplicationInstance`'s `init` method. In my head it pairs nicely with the fact that `ApplicationInstance` is now the one responsible for deregistering.

I don't feel super strongly... What do you think?

File: packages/ember-application/lib/system/application.js [hunk 11]
```diff
@@ -368,7 +380,23 @@ const Application = Engine.extend({
...
+  },
+
+  /**
+    Stop tracking an ApplicationInstance for this application.
+    Used when the ApplicationInstance is about to be destroyed.
+
+    @private
+    @method unwatchInstance
+  */
+  unwatchInstance(instance) {
```
Comment (rwjblue) [inline packages/ember-application/lib/system/application.js]: Should probably be underscored to make it being private more obvious...

File: packages/ember/tests/component_registration_test.js (hunk 7 above)
Comment (mixonic) [reply packages/ember/tests/component_registration_test.js]: Looked into this and although `expectDeprecation` has an async-friendly form `expectAssertion` does not currently. I think a `TODO: Use the async form of expectAssertion here when it is available` would be sufficient.

File: packages/ember-application/lib/system/application.js (hunk 10 above)
Comment (mixonic) [reply packages/ember-application/lib/system/application.js]: Seems like we should make a small refactor to:

* `Application#_unwatchInstance` - does what `unwatchInstance` does now.
* `Application#_watchInstance` - is called by `ApplicationInstance#init` at the beginning of that method. Does the watching bit here.

Comment (rwjblue) [reply packages/ember-application/lib/system/application.js]: Sounds good to me!

File: packages/ember/tests/routing/substates_test.js [hunk 12]
```diff
@@ -436,64 +433,41 @@ moduleFor('Loading/Error Substates', class extends ApplicationTestCase {
...
+      assert.equal(
+        text,
+        'TOPLEVEL ERROR: BAD NEWS BEARS',
+        'toplevel error rendered'
+      );
+    });
 
     reject = false;
 
     return this.visit('/').then(() => {
```
Comment (rwjblue) [inline packages/ember/tests/routing/substates_test.js]: I think this needs to be updated to chain off of the higher up `return this.visit(...)` or it is unreachable...

**Comment by mixonic** [comment]
Ok, I pushed a little more cleanup in a force push to this branch.

* Refactor toward two private APIs on the application for watch/unwatch.
* Fix an early `return` in a test which @rwjblue identified.
* Refactored some tests that were testing internal state on the private-API tracking array to instead test public API behaviors. When an application is destroyed, all application instances it created should also be destroyed.

@krisselden has pointed out that there are several related issues here. The goal of this PR is specifically:

* When an application is destroyed, the application instances it created should be destroyed. Before this patch autoboot application would always correctly do this. After this patch non-autoboot applications also teardown any instances they created.
* Several tests in master use autoboot just so the teardown during testing works correctly. Since we're fixing non-autoboot application to also teardown instances, we can remove the autoboot test helpers (simplifying the tests).

I've changed this back to targeting canary as well, since we don't actually know of any test suites or real app cases impact buy this (though you could theorize them).

**Review by mixonic — APPROVED** [review]

**Comment by kpfefferle** [comment]
I added the above-mentioned `TODO` and then force-pushed. Hopefully the browser tests won't "unexpectedly exit" this time.

**Comment by rwjblue** [comment]
That CI job will fail until https://github.com/emberjs/ember.js/issues/16065 is resolved.

**Comment by mixonic** [comment]
Great, calling this solid then!
