### PR TITLE
Fix view destruction inside outlets

### LINKED ISSUE #11539: [Ember 1.13.1]willDestroyElement never called
I know the view is deprecated, but shouldnt this still work anyway?

here is a jsbin showing the issue, just change to 1.12.1 to see it work
http://emberjs.jsbin.com/puconuxita/edit?html,css,js,console,output

### PR DESCRIPTION
**Pull request by ef4**
This fixes #11539. However, I think it's hacky and this needs review by @wycats and maybe @mmun.

I do not see who is truly responsible for view destruction. HTMLBars is clearing the DOM nodes without destroying corresponding views. This leaves a keyword like `outlet` in an awkward position of needing to destroy views that are already out-of-DOM, which is bad because the views will blindly nuke their original contextual element even though subsequent content may already be present.

### CODE REVIEW

File: packages/ember-metal-views/lib/renderer.js [hunk 1]
```diff
@@ -210,7 +210,7 @@ Renderer.prototype.renderElementRemoval =
     if (view._willRemoveElement) {
       view._willRemoveElement = false;
 
-      if (view._renderNode) {
+      if (view._renderNode && view.element && view.element.parentNode) {
```
Comment (ef4) [inline packages/ember-metal-views/lib/renderer.js]: This is the especially hacky bit. Without this, views that are already out-of-DOM will delete unrelated subsequent content that has replaced them in the same render node.

**Comment by ef4** [comment]
Despite my above caveats, I do think this code is safe to merge and it solves a pressing issue that is blocking people's upgrades. We can address the architectural concern at our leisure.
