### PR TITLE
[Bugfix] fixes bugs around baseURL and rootURL in HistoryLocation and introduces rootURL to NoneLocation

### LINKED ISSUE #13464: FastBoot Bug - Location none doesn't respect rootURL
Location none doesn't respect the router's `rootURL`.  This causes issues while [generating urls](https://github.com/emberjs/ember.js/blob/45248e2fb2c71ec60bb879c7588beeaeffe6dc6c/packages/ember-routing/lib/location/none_location.js#L85-L90) (link-to's for example will omit the `rootURL`).  Compare this to [history's formatURL](https://github.com/emberjs/ember.js/blob/45248e2fb2c71ec60bb879c7588beeaeffe6dc6c/packages/ember-routing/lib/location/history_location.js#L216) and you'll see the difference between implementations.

This is causing issues within the non-browser path of the `visit` API since it [always defaults](https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application-instance.js#L384-L388) to the `none` location.

I would be happy to help patch, but first would like to hear feedback though before venturing off.  For example, do we want to stub out the window.location API when in Node and stick with using the history location, do we patch the none location to respect rootURL in formatURL, or something I'm not thinking of?

Part of this is related to:
https://github.com/ember-fastboot/ember-fastboot-server/issues/53

### PR DESCRIPTION
**Pull request by jasonmit**
Currently `rootURL` isn't respected within `Ember.NoneLocation` and the visit API which results in the route not to be found.

The second bug, `formatURL` also does not return the url with the `rootURL` prefixed.  This breaks `linkto` from building the proper string used in hrefs.

This is blocking projects that rely on `rootURL` to migrate to FastBoot.
- Fixes `baseURL` and `rootURL` from being string replaced at any point in the url for `Ember.HistoryLocation`
- Fixes #13464 https://github.com/ember-fastboot/fastboot/issues/53

### CODE REVIEW

File: packages/ember-application/lib/system/application-instance.js [hunk 1]
```diff
@@ -281,7 +282,8 @@ const ApplicationInstance = EngineInstance.extend({
     // Keeps the location adapter's internal URL in-sync
     get(router, 'location').setURL(url);
 
-    return router.handleURL(url).then(handleResolve, handleReject);
+    // getURL returns the set url with the rootURL stripped off
```
Comment (jasonmit) [inline packages/ember-application/lib/system/application-instance.js]: and base URL if used in the context of the HistoryLocation

File: packages/ember-routing/lib/location/none_location.js [hunk 2]
```diff
@@ -23,14 +23,30 @@ export default EmberObject.extend({
...
   getURL() {
-    return get(this, 'path');
+    let path = get(this, 'path');
+    let rootURL = get(this, 'rootURL');
+
+    // remove trailing slashes if they exists
+    rootURL = rootURL.replace(/\/$/, '');
+
+    // remove rootURL from url
+    return path.replace(rootURL, '');
```
Comment (rwjblue) [inline packages/ember-routing/lib/location/none_location.js]: Given a `rootURL` of `/foo` we want to strip it from `/foo/bar/baz` but we do not want `/foo/baz/foo/bar` to become `/baz/bar`.

File: packages/ember-routing/lib/location/none_location.js [hunk 3]
```diff
@@ -23,14 +23,30 @@ export default EmberObject.extend({
...
     @method getURL
     @return {String} path
   */
   getURL() {
-    return get(this, 'path');
+    let path = get(this, 'path');
+    let rootURL = get(this, 'rootURL');
+
+    // remove trailing slashes if they exists
+    rootURL = rootURL.replace(/\/$/, '');
```
Comment (rwjblue) [inline packages/ember-routing/lib/location/none_location.js]: Can we store the normalized `rootURL` (perhaps in `init`), instead of removing the trailing slash on every `getURL` / `formatURL`?

File: packages/ember-routing/lib/location/none_location.js (hunk 2 above)
Comment (jasonmit) [inline packages/ember-routing/lib/location/none_location.js]: Yup I thought the same.  This was taken from history location.  Want me to fix both?

File: packages/ember-routing/lib/location/none_location.js (hunk 3 above)
Comment (jasonmit) [inline packages/ember-routing/lib/location/none_location.js]: 👍

File: packages/ember-routing/lib/location/none_location.js (hunk 2 above)
Comment (rwjblue) [inline packages/ember-routing/lib/location/none_location.js]: Yes, absolutely!

File: packages/ember-routing/lib/location/none_location.js (hunk 3 above)
Comment (jasonmit) [inline packages/ember-routing/lib/location/none_location.js]: The caveat this introduces is you wouldn't be able to change the rootURL after the router setup.  Unsure if that's an actual use case or not though.  History location is also doing this as well.

**Comment by jasonmit** [comment]
@rwjblue ready for another review -- thanks again

File: packages/ember-routing/lib/location/none_location.js (hunk 3 above)
Comment (rwjblue) [inline packages/ember-routing/lib/location/none_location.js]: Yeah, that makes sense. We could make it a CP with a setter maybe, but I'm not sure it's worth the effort.

**Comment by rwjblue** [comment]
Thanks!

**Comment by jasonmit** [comment]
@rwjblue we should likely force the rootURL to / when in testing.  People likely have relied on this bug, I.e, a computed property as the rootURL or an initializer without checking the environment first.

Thoughts?
