### PR TITLE
[BUGFIX release-1-13] Fix string classify normalizer

### LINKED ISSUE #11326: TextFieldComponent Resolver Issue
We use the default globals resolver in our app, and we have an issue when trying to use the `{{input}}` helper in our app. We just upgraded to 1.13, and apparently, the default component name is now `-text-field`, which resolves to the `TextFieldComponent` that we defined ourselves in our app. I spoke with @rwjblue about this on slack, and we agreed it is a bug that should be looked at.

https://github.com/emberjs/ember.js/blob/bfcc15ee3ac2b2b3e4dad6aa0d7a447936302f5a/packages/ember-htmlbars/lib/keywords/input.js#L24

### PR DESCRIPTION
**Pull request by skeate**
Resolves #11326. If a piece of a name starts with dash (-), it will be changed into an underscore (_).

### CODE REVIEW

File: packages/ember-runtime/lib/system/string.js [hunk 1]
```diff
@@ -28,13 +28,24 @@ var CAMELIZE_CACHE = new Cache(1000, function(key) {
...
+var STRING_CLASSIFY_REGEXP_2 = (/(.)(\-|\_|\.|\s)+(.)?/g);
+var STRING_CLASSIFY_REGEXP_3 = (/(^|\/|\.)([a-z])/g);
 
 var CLASSIFY_CACHE = new Cache(1000, function(str) {
-  return str.replace(STRING_CLASSIFY_REGEXP_1, function(match, separator, chr) {
-    return chr ? chr.toUpperCase() : '';
-  }).replace(STRING_CLASSIFY_REGEXP_2, function(match, separator, chr) {
+  return str
+  .split('/')
+  .map(function(piece) {
```
Comment (rwjblue) [inline packages/ember-runtime/lib/system/string.js]: We can't use `Array.prototype.map` in release-1-13 (because it must support ES3 browsers), can you swap this to a `for` loop instead to allow this to be pulled into those branches?

**Comment by skeate** [comment]
Changed.

**Comment by rwjblue** [comment]
Can you also add tests for these scenarios:

* `classify('_FooBar') === '_FooBar'`
* `classify('_Foo_Bar') === '_FooBar'`
* `classify('_Foo-Bar') === '_FooBar'`
* `classify('_foo/_bar') === '_Foo/_Bar'`
* `classify('-foo/_bar') === '_Foo/_Bar'`
* `classify('-foo/-bar') === '_Foo/_Bar'`

**Comment by skeate** [comment]
Any issue with redoing all these tests as a sort of macro function? i.e. they're all like

```javascript
QUnit.test('classify normal string', function() {
  deepEqual(classify('my favorite items'), 'MyFavoriteItems');
  if (Ember.EXTEND_PROTOTYPES) {
    deepEqual('my favorite items'.classify(), 'MyFavoriteItems');
  }
});
```

-- could write one function

```javascript
function test(description, given, expected) {
  QUnit.test(description, function() {
    deepEqual(classify(given), expected);
    if (Ember.EXTEND_PROTOTYPES) {
      deepEqual(given.classify(), expected);
    }
  });
}
```

Would be easier to write them and easier to see all the different test cases.

**Comment by rwjblue** [comment]
Ya, one commit with the fix and new tests (the old way), and a second commit that refactors to a saner structure sounds great.

**Comment by rwjblue** [comment]
Only the first commit would be `[BUGFIX release-1-13]` though. The other would be `[CLEANUP canary]` I think.

**Comment by skeate** [comment]
alright, have it done in a min

**Comment by rwjblue** [comment]
Looks great, thank you!
