### PR TITLE
[BUGFIX beta] Make sure the `component-class` blueprint generates a signature in a TS project

### LINKED ISSUE #20598: [Bug] `ember g component-class foo` does not generate a component signature in a TypeScript project
### 🐞 Describe the Bug

`ember g component-class foo` does not generate a component signature in a TypeScript project.

### 🔬 Minimal Reproduction

Run `ember g component-class foo` in a TS project.

### 😕 Actual Behavior

```js
import Component from '@glimmer/component';

export default class FooComponent extends Component {}
```

### 🤔 Expected Behavior

```ts
import Component from '@glimmer/component';

interface FooSignature {
  // The arguments accepted by the component
  Args: {};
  // Any blocks yielded by the component
  Blocks: {
    default: []
  };
  // The element to which `...attributes` is applied in the component template
  Element: null;
}

export default class FooComponent extends Component<FooSignature> {}
```

### 🌍 Environment

- Ember: 5.4
- Node.js/npm: /
- OS: /
- Browser: /

### ➕ Additional Context

/

### PR DESCRIPTION
**Pull request by bertdeblock**
Closes https://github.com/emberjs/ember.js/issues/20598.

### CODE REVIEW

File: blueprints/-utils.js [hunk 1]
```diff
@@ -1,9 +1,33 @@
...
+    `  Blocks: {${EOL}` +
+    `    default: []${EOL}` +
+    `  };`;
+
+  let element =
+    `  // The element to which \`...attributes\` is applied in the component template${EOL}` +
+    `  Element: null;`;
+
+  return (
+    `interface ${componentName}Signature {${EOL}` +
```
Comment (dfreeman) [inline blueprints/-utils.js:18]: Generally the guidance we've given with Glint is to always export your signature, since it's useful when you start talking about places where other components are yielding or or accepting this one as an arg.

Comment (bertdeblock) [reply blueprints/-utils.js]: Thanks @dfreeman. Updated accordingly.

**Comment by kategengler** [comment]
Thank you!
