### PR TITLE
[BUGFIX beta] Fix issue with IE9 compatibility.

### LINKED ISSUE #14006: Internet Explorer IE9: _emberEnvironment.environment.global returns `undefined`
After upgrading one of our apps to 2.7, it failed to load in IE9. I reproduced the issue by installing a new sandbox app with v2.7.  The error is thrown in `supportsHashChange` with `global` being `undefined`.

```
function supportsHashChange(documentMode, global) {
    return 'onhashchange' in global && (documentMode === undefined || documentMode > 7);
  }
```

Reverting to 2.6 resolves the issue.

### PR DESCRIPTION
**Pull request by rwjblue**
A past refactor left `AutoLocation` in a broken state under IE9. This fixes that error and adds a (somewhat silly) test.

Fixes #14006.

### CODE REVIEW

**Comment by rwjblue** [comment]
I tested a simple `ember new foo` app with Ember version just before this change under IE9 the following error occurs:

```
SCRIPT5007: Invalid operand to 'in': Object expected 
```

After this change, the error does not occur...

File: packages/ember-routing/lib/location/auto_location.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ export default EmberObject.extend({
    @property global
    @default environment.global
   */
-  global: environment.global,
+  global: environment.window,
```
Comment (Turbo87) [inline packages/ember-routing/lib/location/auto_location.js]: the default above should probably be updated too, right?
