### PR TITLE
[BUGFIX] Ensure tagForProperty works on class constructors

### LINKED ISSUE #17651: `EMBER_METAL_TRACKED_PROPERTIES` fails with Ember Data
@pzuraq 

Testing the `octane` blueprints with Ember Data; `update(propertyTag, tag)` triggers an exception.

screen shot 2019-02-22 at 4 50 18 am

Using a simple model like:

```
export default Model.extend({
  name: attr('string')
});
```

### PR DESCRIPTION
**Pull request by pzuraq**
`tagForProperty` was returning the constant tag for functions, which
meant it would return the constant tag for properties on class
constructors. If a computed property was defined on the class
constructor it would fail because of this.

Fixes #17651

### CODE REVIEW

File: packages/@ember/-internals/metal/lib/tags.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ function makeTag(): TagWrapper<DirtyableTag> {
 }
 
 export function tagForProperty(object: any, propertyKey: string | symbol, _meta?: Meta): Tag {
-  if (typeof object !== 'object' || object === null) {
+  if (typeof object !== 'function' && (typeof object !== 'object' || object === null)) {
```
Comment (rwjblue) [inline packages/@ember/-internals/metal/lib/tags.ts]:
```suggestion
  let objectType = typeof object;
  if (objectType !== 'function' && (objectType !== 'object' || object === null)) {
```

File: packages/@ember/-internals/metal/tests/computed_test.js [hunk 2]
```diff
@@ -82,6 +82,19 @@ moduleFor(
       assert.equal(count, 1, 'should have invoked computed property');
     }
 
+    ['@test computed property can be defined and accessed on a class constructor'](assert) {
```
Comment (rwjblue) [inline packages/@ember/-internals/metal/tests/computed_test.js]: Can we have a native class version of this test too?

```js
class Foo {}
Foo.bar = 123;
Ember.defineProperty(Foo, 'foo', computed(function() { return this.bar; }));
```

**Review by rwjblue — CHANGES_REQUESTED** [review]

**Review by rwjblue — APPROVED** [review]
