### PR TITLE
[BUGFIX beta] Fix issue with `Ember.trySet` on destroyed objects.

### LINKED ISSUE #12356: `Ember.trySet()` throws 'Assertion Failed: calling set on destroyed object'
From the documentation:

> Error-tolerant form of Ember.set. Will not blow up if any part of the chain is undefined, null, or **destroyed**.

1.13.10:
http://emberjs.jsbin.com/sufaji/edit?html,js,console

2.0.2:
http://emberjs.jsbin.com/yafacu/edit?html,js,console

Open up the console to see the assertion error.

### PR DESCRIPTION
**Pull request by rwjblue**
`Ember.trySet` is designed to be an error-tolerant form of `Ember.set` (per its public API documentation). However, in some circumstances an error is still thrown when setting on a destroyed object.

Prior to this change, the following would properly prevent an error:

``` js
let obj = { some: { deep : 'path', isDestroyed: true }};

Ember.trySet(obj, 'some.deep', 'stuff');
```

But the following would throw an error incorrectly:

``` js
let obj = { some: 'path', isDestroyed: true };

Ember.trySet(obj, 'some', 'stuff');
```

This fixes the latter case...

Fixes #12356.

### CODE REVIEW

**Comment by rwjblue** [comment]
@krisselden / @stefanpenner - r?

**Comment by stefanpenner** [comment]
Looks ok, but now that if conditional won't be stripped

**Comment by rwjblue** [comment]
@stefanpenner - Yep, (a similar `if` is also present in `setPath` below this). If I embed the check into the assertion itself (which is possible) then we would actually do a `set` on a destroyed object when in production (because there is nothing left in the code to do a short-circuit).  Is that better?

**Comment by stefanpenner** [comment]
Oops you are correct. This looks good to me

**Comment by rwjblue** [comment]
@krisselden - Any objections?

**Comment by rwjblue** [comment]
I'm going to assign to @krisselden for review.  I want to make sure that we are all happy/ok with this...

**Comment by krisselden** [comment]
I'm ok with this, though, isDestroyed isn't really an ember-metal concept, we should have a value we set meta to, to mean it is destroyed.

Maybe then we could fix the long standing issue of recreating meta() on a destroyed object.
/cc @stefanpenner

**Comment by rwjblue** [comment]
@krisselden - Would you prefer that to happen in this PR or can it happen subsequently?

**Comment by krisselden** [comment]
It can be after, I'm sure enforcing not recreating meta will expose some bugs

**Comment by krisselden** [comment]
Please though open a tracking issue, I keep forgetting about. I think our teardown sometimes recreates the mets itself

File: packages/ember-metal/lib/property_set.js [hunk 1]
```diff
@@ -62,8 +62,11 @@ export function set(obj, keyName, value, tolerant) {
     return setPath(obj, keyName, value, tolerant);
   }
 
-  assert(`calling set on destroyed object: ${toString(obj)}.${keyName} = ${toString(value)}`,
-         !obj.isDestroyed);
+  if (obj.isDestroyed) {
```
Comment (stefanpenner) [inline packages/ember-metal/lib/property_set.js]: @krisselden should we actually allow setting through destroyed objects or to the descs? My intuition leads me to believe this should actually occur before line 53.

Comment (stefanpenner) [inline packages/ember-metal/lib/property_set.js]: basically 3 scenarios exist.

1. set on plain object property
2. set on descriptor
3. set on deep object

We currently guard/assert for 1, and I believe we must absolutely also guard/assert for 2. I also believe we should consider the same for 3, if others disagree I would like to be convinced.

**Comment by vvohra** [comment]
I was wondering about the status of this PR.

Looking at this [twiddle](https://ember-twiddle.com/cfe9901bb9d15917bde3b7b3375af1f1?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs) and checking the console, it seems the issue is still valid on Ember 2.12.

**Comment by mmun** [comment]
@rwjblue I've rebased this PR onto master.
