### PR TITLE
[BUGFIX release] Prevent triggering V8 memory leak bug through registry / resolver access.

### LINKED ISSUE #12618: Memory on acceptance tests on ember 1.13.10+
test repo: https://github.com/calderas/leaky-mcleakerson

After upgrading our app to ember 1.13 chrome crashes when running Acceptance Tests

```
V8 error: Allocation failed - process out of memory (CALL_AND_RETRY_LAST).  Current memory usage: 1949 MB
```

Following the same approach as https://github.com/emberjs/ember.js/issues/11748 I ran some tests on a simple app to compare different versions of ember

### Observations: 
* Memory drops when running unit tests on ember 1.12.
* Memory allocated for tests is  ~ twice on ember 1.13 & 2.1 for same app.
* Memory allocation tends to increase overtime on acceptance tests.

### Questions:
* Is this expected ?
* Thoughts on how to debug further ?

### Memory comparison

screen shot 2015-11-16 at 12 59 31 pm
screen shot 2015-11-16 at 12 58 20 pm
screen shot 2015-11-16 at 12 58 49 pm

Looking at the timeline seems like event listeners remain after tests have completed and detached elements show up on heap profiles.

ef067318-892c-11e5-8a4d-fe75297533cb
f09d0494-892c-11e5-8c0f-aba694f2b135

test repo: https://github.com/calderas/leaky-mcleakerson

### PR DESCRIPTION
**Pull request by dgeb**
This fix changes the expectations of Registry to accept a `resolver` 
that’s an object with a `resolve` method instead of a straight function.

This allows us to avoid closing over access to a resolver object inside 
a function. It also allows us to avoid setting functions which shadow 
prototype functions unnecessarily.

Setting `Registry#resolver` to a function is still allowed but 
deprecated, regardless of whether it’s through a constructor option or 
via an instance override. The `resolver` function will be converted into
an object with a `resolve` method and will present a single deprecation 
warning on first access.

This fix also eliminates the need for application instances to override
their registry’s `normalizeFullName` and `makeToString` methods. 
Instead, the fallback registry will be checked when evaluating these
methods before returning the defaults. Again, this avoids the need to
override instance functions that shadow prototype functions.

[Fixes #12618]

/cc @rwjblue @stefanpenner

### CODE REVIEW

File: packages/container/lib/registry.js [hunk 1]
```diff
@@ -723,12 +749,30 @@ Registry.prototype = {
...
-  var cached = registry._resolveCache[normalizedName];
+  let cached = registry._resolveCache[normalizedName];
   if (cached) { return cached; }
   if (registry._failCache[normalizedName]) { return; }
 
-  var resolved = registry.resolver(normalizedName) || registry.registrations[normalizedName];
+  let resolved;
+
+  if (registry.resolver) {
+    if (typeof registry.resolver === 'function') {
```
Comment (rwjblue) [inline packages/container/lib/registry.js]: Since `registry.resolver` is already taken care of in `Registry`'s constructor, we should be able to remove this extra conditional.  I do not believe that changing the resolver after registry creation is a thing we should support...

Comment (dgeb) [inline packages/container/lib/registry.js]: Ok, I'll remove this check and the corresponding test.

**Comment by rwjblue** [comment]
Looks good other than that one comment about lazily assigning `resolver` function.

**Comment by dgeb** [comment]
Ok, thanks for the review @rwjblue. I just eliminated the ability to lazily assign `resolver` as a function (which can now only be done through the constructor).

**Comment by rwjblue** [comment]
We still need confirmation from @stefanpenner that this fixes the leak he reported in #12618, but this is still a good refactor (and replaces some fairly gnarly code!) so I'm going to land this into canary + beta.  Once confirmed RE: the leak (and that we don't introduce issues with this change into beta/canary) we can pull into release branch (currently 2.2.x).

**Comment by marcoow** [comment]
I guess this requires changes to ember-test-helpers `setResolver`? Currently this change breaks the Ember Simple Auth build (https://travis-ci.org/simplabs/ember-simple-auth/jobs/94633282) with `TypeError: registry.resolver.resolve is not a function` at https://github.com/dgeb/ember.js/blob/529bfc3bbfa1c1a96d51a085fcc6394101d8ea6f/packages/container/lib/registry.js#L769.

Would be happy to fix that if you guys can point me in the right direction - I'm not really sure where to start yet…

**Comment by rwjblue** [comment]
@marcoow - We are tracking that issue over in ember-test-helpers https://github.com/switchfly/ember-test-helpers/pull/126 and https://github.com/switchfly/ember-test-helpers/pull/127.  Hoping to get a fix out today...

**Comment by marcoow** [comment]
@rwjblue: great; let me know if I can help!

**Comment by poteto** [comment]
Just to add another instance of the issue @marcoow is having in https://github.com/poteto/ember-metrics/pull/55. For context, I worked through with @rwjblue on refactoring deprecated use of `lookupFactory` through setting `{ instantiate: false }` on `registerOptionsForType` in the new `getOwner` API.

Tests are only failing in `beta` and `canary`.

screenshot 2015-12-07 12 11 58
