### PR TITLE
[BUGFIX release] Prevent multiple qp serialization on activeTransition

### LINKED ISSUE #14174: Correct Query String Serialization and Deserialization
This bug supersedes #13816 and #14171 (and who knows how many others). The behavior for serializing objects to query strings inside of Ember is wrong for at least two reasons:
1. It is inconsistent with literally every other implementation I've reviewed (~20 at this point).
2. It does not match the behavior of `route-recognizer`, which we also bundle.

This means that our behavior does not work on hard refresh and also triggers strange serialization inconsistencies when run through a `string` or `object` path. I'm writing a full blog post about query strings which will be published this week which will detail a path forward.
- [Implementation in Ember.](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/route.js#L421-L464)
- [`route-recognizer`'s `parseQueryString`.](https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer.js#L455-L483)
- [`route-recognizer`'s `generateQueryString`.](https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer.js#L423-L453)

I'm of the opinion that we should not attempt patches to this behavior without solving the underlying problem as we will simply introduce new and different failure modes. Until we have a complete solution (which I'll write as part of landing the new `route-recognizer`) we should ride out our existing known behavior and new reports should be closed as a duplicate of this bug.

### PR DESCRIPTION
**Pull request by rreckonerr**
We're using serialized query parameters for active transition instead of deserialized ones. This results in multiple serialization of qp's.

Closes #14174

### CODE REVIEW

File: packages/ember/tests/routing/query_params_test.js [hunk 1]
```diff
@@ -137,6 +137,55 @@ moduleFor(
...
+      this.add(
+        'controller:parent',
+        Controller.extend({
+          queryParams: ['array', 'string'],
+          array: [],
+          string: '',
+        })
+      );
+
+      // `/parent/child?array=["one",2]&string=hello`
```
Comment (rreckonerr) [inline packages/ember/tests/routing/query_params_test.js:170]: @chancancode @rwjblue 

This test case fails with not really helpful error:
```json
Promise rejected during " Calling transitionTo does not serialize multiple times query params already on the activeTransition": Assertion Failed: Cannot call `meta` on string
```

Which comes from `emberA` trying to convert a string to array.
```ts
emberA(JSON.parse(value as string)`
```
https://github.com/emberjs/ember.js/blob/20da5b22c9afc287dd4fef206ce7a9b3de0933d6/packages/%40ember/-internals/routing/lib/system/router.ts#L786-L797

But this error is not thrown in an ember application.

Wrapping `emberA(JSON.parse(value as string)` in a try-catch block results in failing test assertion. 

Should we do something to improve error reporting in `_deserializeQueryParam`? Like, check if `JSON.parse(value)` actually returns an array?

Comment (rwjblue) [reply packages/ember/tests/routing/query_params_test.js:170]: > Should we do something to improve error reporting in _deserializeQueryParam? Like, check if JSON.parse(value) actually returns an array?

Yes, I think this seems like the best path.

**Review by rwjblue — APPROVED** [review]
