### PR TITLE
[BUGFIX beta] Make toString safe for arrays too.

### LINKED ISSUE #14738: Cannot convert object to primitive value
This is similar to https://github.com/emberjs/ember.js/issues/14187, but I have a reproduction in Ember 2.10 with no addons:

https://ember-twiddle.com/4df2d62bf5f1c05bd74086dc79326020?openFiles=components.my-component.js%2C

The critical ingredient seems to be that I am taking an object created by the `hash` helper, putting it inside an `Array`, and passing the array into another component. When such an array hits `toString` it causes an exception.

(It's hitting `toString` in the first place to support an assertion.)

### PR DESCRIPTION
**Pull request by Serabe**
`ember-utils/to-string` is documented as a `toString` function that supports
objects without a `toString` method.

Arrays do have a string method that is based on their `join` method. This
method spec ([Array.prototype.join in ecma262 2017
draft](https://tc39.github.io/ecma262/#sec-array.prototype.join)) is based on
calling `toString` on the objects that form the collection. If an object were
not to have such method, `Array.prototype.toString` would throw and error.

This PR recreates `Array.prototype.join` as closer to the spec as I could,
changing the `ToString` part with the safe version of `toString`.

Fixes #14738 and #15113.

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]
This is _slightly_ annoying to have to ship, but I think it is a good solution to a fairly gnarly problem.  Another solution would be to have the `(hash` helper return a "regular" object with a `.toString` method (which of course possibly pollutes).

Seems good to me...

File: packages/ember-utils/lib/to-string.js [hunk 1]
```diff
@@ -1,11 +1,33 @@
...
+        r += ',';
+      }
+
+      if (!isNone(obj[k])) {
+        r += toString(obj[k]);
+      }
+    }
+
+    return r;
+  } else if (obj && typeof obj.toString === 'function') {
```
Comment (stefanpenner) [inline packages/ember-utils/lib/to-string.js]: can `obj` be some `truthy` non object?

Comment (Serabe) [inline packages/ember-utils/lib/to-string.js]: Would `!isNone(obj) && typeof obj.toString === 'function'` be ok?

Comment (stefanpenner) [inline packages/ember-utils/lib/to-string.js]: `typeof obj === 'object' && !== obj && typeof obj.toString === 'function'` should do the trick

Comment (Serabe) [inline packages/ember-utils/lib/to-string.js]: That would not work for strings.

Comment (stefanpenner) [inline packages/ember-utils/lib/to-string.js]: yes, strings should be a short circuit at the root of the function.

```js
if (typeof obj === 'string') { return obj; }
```

invoking `string.toString()` seems funky?

Comment (stefanpenner) [inline packages/ember-utils/lib/to-string.js]:
```js
let type = obj;

if (type === 'string') { return obj; }
if (Array.isArray(obj)) { /* do new stuff */}
else if (obj !== null && typeof obj.toString === 'function') {
   return obj.toString();
} else {
   return objectToString.call(obj); 
}
```

**Comment by Serabe** [comment]
Restarting sauce.

**Comment by Serabe** [comment]
Tests are passing now

**Comment by notmessenger** [comment]
If you are looking for this fix it wasn't released until `2.13.0` on 27 Apr 2017 (https://github.com/emberjs/ember.js/blob/v2.13.0/packages/ember-utils/lib/to-string.js)

**HOWEVER...**

It **was** merged into the `#lts-2-12` branch on 27 Apr 2017 (https://github.com/emberjs/ember.js/blob/lts-2-12/packages/ember-utils/lib/to-string.js)
