### PR TITLE
[BUGFIX] Fix trackedMap and trackedWeakMap reactivity for existing keys

### LINKED ISSUE #21123: `trackedMap().set()` does not dirty collection tag for existing keys, breaking iteration consumers
### 🐞 Describe the Bug

`trackedMap().set()` from `@ember/reactive/collections` does not dirty the collection tag when updating an existing key whose stored value is truthy. This means getters that consume iteration methods (`.values()`, `.entries()`, `.forEach()`) will not re-evaluate when existing entries are updated.

The root cause is in [`TrackedMap.set()`](https://github.com/emberjs/ember.js/blob/02c62b0d7cbec49271949fcf608e66f1ccb5b3a6/packages/%40glimmer/validator/lib/collections/map.ts#L130-L150):

```typescript
set(key: K, value: V): this {
  let existing = this.#vals.get(key);

  if (existing) {
    let isUnchanged = this.#options.equals(existing, value);

    if (isUnchanged) {
      return this;
    }
  }

  this.#dirtyStorageFor(key);

  if (!existing) {
    DIRTY_TAG(this.#collection);
  }

  this.#vals.set(key, value);

  return this;
}
```

`existing` holds the raw stored **value** from `this.#vals.get(key)` (not a boolean). The `if (existing)` and `if (!existing)` checks use value **truthiness** instead of `this.#vals.has(key)`. This causes two problems:

1. When a key exists with a **truthy** value (object, non-zero number, non-empty string): `if (!existing)` is `false` → collection tag is **never dirtied**, even though the value changed.
2. When a key exists with a **falsy** value (`0`, `false`, `""`, `null`): `if (existing)` is `false` → equality check is **skipped**, and `if (!existing)` is `true` → collection tag is dirtied even when value hasn't changed.

Since `.values()`, `.entries()`, and `.forEach()` only consume `this.#collection` (not per-key storage tags), they miss the update in case 1.

`.get(key)` and `.has(key)` are unaffected (they consume per-key storage tags). `[Symbol.iterator]()` also happens to work because it calls `self.get(currentKey)` internally.

This is a behavioral regression from [`tracked-built-ins` (old path, Ember < 6.8)](https://github.com/tracked-tools/tracked-built-ins/blob/master/addon/src/-private/old/map.ts) which unconditionally dirties the collection tag on `set()`:

```typescript
set(key, value) {
  this.dirtyStorageFor(key);
  setValue(this.collection, null);  // unconditional
  this.vals.set(key, value);
  return this;
}
```

Note: `tracked-built-ins` v3's [new path (Ember >= 6.8)](https://github.com/tracked-tools/tracked-built-ins/blob/master/addon/src/-private/new/map.ts) wraps native `trackedMap()` with `{ equals: () => false }`, which disables the value equality short-circuit but does NOT fix the `existing || DIRTY_TAG(...)` issue. So `tracked-built-ins` on Ember >= 6.8 is also affected for truthy stored values.

If this is considered intentional behavior rather than a bug, we believe it should be explicitly documented in the `@ember/reactive/collections` API docs — the current docs don't mention that iteration consumers won't see updates to existing Map entries.

### 🔬 Minimal Reproduction

```javascript
import { trackedMap } from '@ember/reactive/collections';
import { cached } from '@glimmer/tracking';

const map = trackedMap([['a', { count: 1 }]]);

class Reader {
  @cached
  get total() {
    let sum = 0;
    for (const v of map.values()) {
      sum += v.count;
    }
    return sum;
  }
}

const reader = new Reader();
console.log(reader.total); // 1

map.set('a', { count: 42 }); // Updates existing key with truthy value
console.log(reader.total); // Still 1 — getter not re-evaluated
```

### 😕 Actual Behavior

After calling `map.set('a', { count: 42 })` to update an existing key, a `@cached` getter that iterates via `.values()` returns the stale value (`1`) because the collection tag was not dirtied.

### 🤔 Expected Behavior

The `@cached` getter should re-evaluate and return `42`, since the map's contents have changed. This is how [`tracked-built-ins` (old path, Ember < 6.8)](https://github.com/tracked-tools/tracked-built-ins/blob/master/addon/src/-private/old/map.ts) behaves — it unconditionally dirties the collection tag on `set()`.

### 🌍 Environment

- Ember: 6.10.1
- Node.js/npm: 25.x / pnpm 9.x
- OS: macOS

### ➕ Additional Context

**Suggested fix:** The `set()` method's truthiness checks should use `this.#vals.has(key)` instead of relying on value truthiness (to fix the falsy value edge case). But the deeper issue is that `.values()`, `.entries()`, and `.forEach()` only consume the collection tag, so they miss per-key value updates.

`[Symbol.iterator]()` already solves this correctly by calling `self.get(currentKey)` per iteration, which consumes per-key storage tags. The other methods could delegate to it:

```typescript
values() {
  let iterator = this[Symbol.iterator]();
  return {
    next() {
      let { value, done } = iterator.next();
      return done ? { value: undefined, done } : { value: value[1], done };
    },
    [Symbol.iterator]() { return this; },
  } as IterableIterator<V>;
}

entries() {
  return this[Symbol.iterator]();
}

forEach(fn: (value: V, key: K, map: Map<K, V>) => void): void {
  for (let [key, value] of this) {
    fn(value, key, this);
  }
}
```

Note: [RFC #1068](https://rfcs.emberjs.com/id/1068-tracked-collections/) does not explicitly specify this behavior — it doesn't mention whether iteration consumers should see updates to existing entries or whether the collection tag should be dirtied on value updates.

### PR DESCRIPTION
**Pull request by megothss**
`TrackedMap.set()` and `TrackedWeakMap.set()` use value truthiness (`if (existing)`) instead of `this.#vals.has(key)` to check for existing keys, causing two bugs:

1. **Existing truthy values**: The equality check runs but the collection tag is never dirtied, so iteration consumers (`.values()`, `.entries()`, `.forEach()`) miss value updates
2. **Existing falsy values** (`0`, `false`, `null`, `""`): The equality check is skipped entirely, and the collection tag is dirtied unnecessarily

Additionally, TrackedMap's `.entries()`, `.values()`, and `.forEach()` only consume the collection tag, so they miss per-key value updates even with a correct `set()`. This is in contrast to `[Symbol.iterator]()` which correctly consumes per-key storage tags via `self.get()`.

### Changes

**TrackedMap:**
- **`set()`**: Replace value truthiness checks with `this.#vals.has(key)`
- **`entries()`, `values()`, `forEach()`**: Delegate to `[Symbol.iterator]()` which already correctly consumes both the collection tag and per-key storage tags
- **`[Symbol.iterator]()`**: Add `[Symbol.iterator]()` to the returned object so it satisfies the iterable protocol (needed by `entries()` and `for...of` consumers)
- **Tests**: Add integration tests for `values`, `entries`, `forEach` with existing key updates, and a test for setting existing falsy values

**TrackedWeakMap:**
- **`set()`**: Same truthiness bug fix — replace `this.#vals.get(key)` with `this.#vals.has(key)`
- **Tests**: Add integration test for setting existing falsy values

Fixes #21123

### CODE REVIEW

File: packages/@glimmer/validator/lib/collections/map.ts [hunk 1]
```diff
@@ -121,6 +127,9 @@ class TrackedMap<K = unknown, V = unknown> implements Map<K, V> {
         // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
         return { value: [currentKey, self.get(currentKey!)], done: false };
       },
+      [Symbol.iterator]() {
```
Comment (NullVoxPopuli) [inline packages/@glimmer/validator/lib/collections/map.ts:132]: nice

File: packages/@glimmer/validator/lib/collections/map.ts [hunk 2]
```diff
@@ -82,15 +80,23 @@ class TrackedMap<K = unknown, V = unknown> implements Map<K, V> {
...
+        return this;
+      },
+    } as MapIterator<V>;
   }
 
   forEach(fn: (value: V, key: K, map: Map<K, V>) => void): void {
-    consumeTag(this.#collection);
-
-    this.#vals.forEach(fn);
+    for (let [key, value] of this) {
```
Comment (NullVoxPopuli) [inline packages/@glimmer/validator/lib/collections/map.ts:97]: does the collection tag not need to be entangled here anymore? I see it's not in entries or the symbol iterator either 🤔

File: packages/@glimmer/validator/lib/collections/map.ts [hunk 3]
```diff
@@ -129,10 +138,10 @@ class TrackedMap<K = unknown, V = unknown> implements Map<K, V> {
   }
 
   set(key: K, value: V): this {
-    let existing = this.#vals.get(key);
+    let existing = this.#vals.has(key);
```
Comment (NullVoxPopuli) [inline packages/@glimmer/validator/lib/collections/map.ts]: can we rename existing here to `hasExisting` or similar?

existing (a noun) more represents a value of something, which I guess booleans are, -- but the context here is that we're asking a question about if the underlying collection has a value for key

File: packages/@glimmer/validator/lib/collections/weak-map.ts [hunk 4]
```diff
@@ -51,10 +51,10 @@ class TrackedWeakMap<K extends WeakKey = object, V = unknown> implements WeakMap
   }
 
   set(key: K, value: V): this {
-    let existing = this.#vals.get(key);
+    let existing = this.#vals.has(key);
```
Comment (NullVoxPopuli) [inline packages/@glimmer/validator/lib/collections/weak-map.ts]: same here

**Comment by NullVoxPopuli** [comment]
legend. I'm optimistic we can get CI fixed today, so we can have a bit more confidence in the fixes and actually get them merged <3

File: packages/@glimmer/validator/lib/collections/map.ts (hunk 2 above)
Comment (megothss) [reply packages/@glimmer/validator/lib/collections/map.ts:97]: The collection tag is still entangled!

It's consumed transitively: 
- `forEach` uses `for...of this` 
- `[Symbol.iterator]()` 
- `this.keys()`
- **`consumeTag(this.#collection)`**

It's the same for `entries()` and `values()`.

I've updated the JSDoc on [Symbol.iterator] to make this clearer.

Comment (NullVoxPopuli) [reply packages/@glimmer/validator/lib/collections/map.ts:97]: thank you!!!!

**Comment by NullVoxPopuli** [comment]
GH is missing a commit :thinking: 

edit: finally! it showed up

**Review by NullVoxPopuli — APPROVED** [review]
