### PR TITLE
[BUGFIX beta] {{link-to}} before application boot

### LINKED ISSUE #11150: On Glimmer, components with `{{link-to}}` fail unit tests
Make a component with a `{{link-to}}` in it. Try to unit test it. You'll get a failure due to a missing router. This worked on canary prior to glimmer being merged.

### PR DESCRIPTION
**Pull request by tomdale**
Previously, {{link-to}} would work even if the application had not been booted completely. This behavior is relied on by test harnesses like ember-qunit, since an “integration test” of a component may include a template that uses {{link-to}}. Many people have discovered that they would like to test a component that has a link without booting the entire app.

> You wanted a banana but what you got was a gorilla holding the banana and the entire jungle. –Joe Armstrong

During the Glimmer work, we refactored the interface between the LinkComponent and the router into a service. Unfortunately, this caused a regression where rendering the link before the router was completely initialized would raise an exception.

This commit adds a very stupid guard to ensure that we have enough router state to determine if a link is active or not. This whole path could be significantly cleaned up, and in particular, we should move towards using a stubbed routing service in tests that encapsulates all of these concerns.

Fixes #11150.

### CODE REVIEW

File: packages/ember/tests/helpers/link_to_test.js [hunk 1]
```diff
@@ -95,6 +96,30 @@ QUnit.module('The {{link-to}} helper', {
...
+// so the container is available but it does not boot the entire app
+QUnit.test('Using {{link-to}} does not cause an exception if it is rendered before the router has started routing', function(assert) {
+  Router.map(function(match) {
+    this.route('about');
+  });
+
+  registry.register('component-lookup:main', ComponentLookup);
+
+  let component = Ember.Component.extend({
+    layout: compile('{{#link-to  "about"}}Go to About{{/link-to}}'),
```
Comment (mixonic) [inline packages/ember/tests/helpers/link_to_test.js]: wacky double space after `link-to`

**Comment by mixonic** [comment]
lgtm!

File: packages/ember/tests/helpers/link_to_test.js [hunk 2]
```diff
@@ -95,6 +96,30 @@ QUnit.module('The {{link-to}} helper', {
   teardown: sharedTeardown
 });
 
+// This test is designed to simulate the context of an ember-qunit/ember-test-helpers component integration test,
+// so the container is available but it does not boot the entire app
+QUnit.test('Using {{link-to}} does not cause an exception if it is rendered before the router has started routing', function(assert) {
+  Router.map(function(match) {
```
Comment (rwjblue) [inline packages/ember/tests/helpers/link_to_test.js]: Not using match AFAICT

**Comment by chadhietala** [comment]
:+1:  /cc @nathanhammond

File: packages/ember/tests/helpers/link_to_test.js (hunk 1 above)
Comment (tomdale) [inline packages/ember/tests/helpers/link_to_test.js]: Actually @mixonic this is intentional. Many people see code as a dead thing, cold symbols to instruct the unfeeling machine what to do. However, the truth is that code, like any living being, is coursing with energy and its own sense of purpose. Here, I could intuitively feel that the `{{link-to}}` helper was feeling constrained by being forced into such close proximity with the argument, badly damaging the feng shui of this file.

lol j/k I fixed it

Comment (jmurphyau) [inline packages/ember/tests/helpers/link_to_test.js]: LOL
