### PR TITLE
[BUGFIX release-1-13] Ensure concatenatedProperties are not stomped.

### LINKED ISSUE #12099: concatenatedProperties works in 1.13.6 but not obliged in 1.13.7+
The issue can be seen here:

http://emberjs.jsbin.com/gaqujefuce/edit?html,css,js,output

Toggle the emberjs version string to see when it starts to fail.

---
`{{ x-foo bar="quux"}}`  when `bar` is set to `["baz"]` in component and `concatenatedProperties: ['bar']`

- 1.13.6: bar equals `['baz', 'quux']`
- 1.13.7 `bar` equals `quux'` 
  - I'm not entirely certain if this is the correct behavior and I'm missing some documentation somewhere.

This was exposed when I began digging into https://github.com/yapplabs/ember-modal-dialog/issues/71.

### PR DESCRIPTION
**Pull request by rwjblue**
When `_propagateAttrsToThis` is invoked it iterates all properties that are present in `this.attrs` and calls `this.set(attrName, attrValue)`.  This is normally exactly what you expect. However, in the case of `concatenatedProperties` and `mergedProperties` this `set`ing causes the concatenated / merged property to be completely clobbered.

The fix introduced in #12073 adds a very simple work around for the internally known items (just hard coding things like `classNames`, `classNameBindings`, `attributeBindings`, and `actions`). This was obviously a very naive check, and leaves any external usages of `concatenatedProperties` in components/views completely hosed.

---

The changes here introduces a __avoidPropagating property that we can use to prevent `concatenatedProperties` and `mergedProperties` from being set inside `_propagateAttrsToThis`. To avoid introducing this cost for every component created (when only classes can define new concatenated / merged properties) we are storing the `__avoidPropagating` on the constructor itself.

One notable addon that has broken functionality is [yapplabs/ember-modal-dialog#71](https://github.com/yapplabs/ember-modal-dialog/issues/71).

---

Fixes #12099.

Implemented by @rondale-sc and @rwjblue.

### CODE REVIEW

**Comment by lukemelia** [comment]
Thanks for tracking this down, gents!

File: packages/ember-views/lib/compat/attrs-proxy.js [hunk 1]
```diff
@@ -16,6 +17,26 @@ function isCell(val) {
 let AttrsProxyMixin = {
   attrs: null,
 
+  init() {
+    this._super(...arguments);
+
+    if (!this.constructor.__avoidPropagating) {
+      this.constructor.__avoidPropagating = dictionary(null);
```
Comment (stefanpenner) [inline packages/ember-views/lib/compat/attrs-proxy.js]: @rwjblue this should likely be an empty object

**Comment by rwjblue** [comment]
Updated with some tweaks suggested by @stefanpenner in chat.

**Comment by rondale-sc** [comment]
@rwjblue Why `EmptyObject` over `dictionary` in this case?

**Comment by rwjblue** [comment]
@stefanpenner explained it to me like this in chat:

Use dictionary for long lived dictionary's that will have many add / removes over time. 

EmptyObject is like 10x faster than Object.create(null) (which is done by dictionary) and is better suited for this kind of thing because we aren't actually going to delete entries.

**Comment by stefanpenner** [comment]
> EmptyObject is like 10x faster than Object.create(null) (which is done by dictionary) and is better suited for this kind of thing because we aren't actually going to delete entries.

Dictionary is for things that will most likely be deleted from

dictionary could also use EmptyObject, but its also the deletion that makes it slow (although it would be less slow once moved to EmptyObject)

**Comment by rondale-sc** [comment]
:+1:  Thanks.  I'm going to look up some of these optimizations so I can have a little bit of a better understanding.  :)

**Comment by sukima** [comment]
Will this be part of a bug fix release on version 1.13? This is a show stopper as the expectation declared in the documentation is broken. Many people (including us) can not upgrade to 2.0 yet.

If not can we have a work around best practice to handle the broken behavior till we can upgrade to 2.0?

**Comment by rwjblue** [comment]
@sukima - Yes, we plan to release a 1.13.x version with this fix.

**Comment by rondale-sc** [comment]
@sukima You can downgrade to 1.13.6 if you need immediate relief.  If that is an option of course.

**Comment by sukima** [comment]
@rwjblue and @rondale-sc thank you!
