### PR TITLE
[BUGFIX canary] Fix exception swallowing in transitions

### LINKED ISSUE #10311: Exception swallowing within willTransition
When you have an exception thrown from within `willTransition` the exception gets swallowed and the router breaks in a very subtle way.

This took quite awhile to triage, as I originally thought the bug was within queryparams and the LinkView.

## Steps to reproduce:
* http://jsbin.com/kevisujowa
* Type anything in the `foo` input
* Notice the queryParam updates as expected
* Now click on the Bar `link-to` and notice that query param was pushed onto the new route's URL (side effect of the bug)
* Notice that in the console you don't see a stacktrace from the `throw new Error()`

## Excepted:
* `throw new Error()` should emit a stacktrace in the console

### PR DESCRIPTION
**Pull request by ef4**
This closes #10311 and a class of related bugs.

The strategy here is to stop trying to handle and log rejections inside the router, and instead trust the global RSVP error handler.

Some test changes were needed because tests were relying on the promise-suppressing behavior.

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

Seems like Travis is angry though.

**Comment by stefanpenner** [comment]
Needs a rebase

**Comment by truenorth** [comment]
This may also fix #10926

File: packages/ember-runtime/lib/ext/rsvp.js [hunk 1]
```diff
@@ -61,7 +66,9 @@ export function onerrorDefault(e) {
         Test.adapter.exception(error);
         Logger.error(error.stack);
       } else {
-        throw error;
+        Ember.run.schedule(Ember.run.queues[Ember.run.queues.length-1], function() {
```
Comment (stefanpenner) [inline packages/ember-runtime/lib/ext/rsvp.js]: i wonder if we should add `final` bucket, that does not allow re-entry?

**Comment by stefanpenner** [comment]
@ef4 got some time to wrap this up?

**Comment by ef4** [comment]
It's green, quick, merge it! Only took me four months.

**Comment by rwjblue** [comment]
Thanks @ef4!

File: packages/ember-runtime/lib/ext/rsvp.js (hunk 1 above)
Comment (krisselden) [inline packages/ember-runtime/lib/ext/rsvp.js]: I want to add a method of getting a promise for the next flush to the backburner refactor.
