### PR TITLE
[BUGFIX release] Fix get with empty string

### LINKED ISSUE #11204: String.length returns undefined for empty string in 1.12
JSBin: http://emberjs.jsbin.com/peposiconi/1/edit?html,js,console,output

It seems that in 1.12 accessing the length property of an empty string through a getter returns `undefined` rather than`0`.

Previously zero was returned as expected.

It looks like this got broken here: https://github.com/emberjs/ember.js/commit/1a3dde2ef03a63db1bb0e5b41fad57f0744fc438#diff-1b9682e6b936bfe3101e35ff6e574957R61

Proposed fix: https://github.com/emberjs/ember.js/compare/master...paddyobrien:paddy/get-empty-string-length

### PR DESCRIPTION
**Pull request by paddyobrien**
Fixes https://github.com/emberjs/ember.js/issues/11204

The change introduced here: https://github.com/emberjs/ember.js/commit/1a3dde2ef03a63db1bb0e5b41fad57f0744fc438#diff-1b9682e6b936bfe3101e35ff6e574957R61 introduced this issue because it assumed that a falsey `obj` always meant it was not present. However if `obj` is a string it can be both falsey and present.

### CODE REVIEW

File: packages/ember-metal/lib/property_get.js [hunk 1]
```diff
@@ -62,7 +62,7 @@ export function get(obj, keyName) {
   Ember.assert(`Cannot call get with ${keyName} key.`, !!keyName);
   Ember.assert(`Cannot call get with '${keyName}' on an undefined object.`, obj !== undefined);
 
-  if (!obj) {
+  if (!obj && typeof obj !== 'string') {
```
Comment (rwjblue) [inline packages/ember-metal/lib/property_get.js]: I think an `isNone` (via `import isNone from 'ember-metal/is_none';`) check here would be better  than specifically checking for strings.

Comment (paddyobrien) [inline packages/ember-metal/lib/property_get.js]: Thanks, yes that's much neater.

**Comment by rwjblue** [comment]
Looks good.

@mixonic / @stefanpenner / @krisselden - Would one of y'all mind reviewing also?

**Comment by stefanpenner** [comment]
looks ok

**Comment by paddyobrien** [comment]
It looks to be a regression in 1.12, see http://emberjs.jsbin.com/peposiconi/1/edit?html,js,console,output

**Comment by rwjblue** [comment]
@stefanpenner - This was introduced by https://github.com/emberjs/ember.js/pull/3852 which initially landed in 1.12 (it sat as a PR for a very long time).  The behavior prior to https://github.com/emberjs/ember.js/pull/3852 was to check `obj === null` (instead of `!obj`), this was changed so that it also applied to `undefined` as of that PR.  

Short version: yes, it is a regression in 1.12 that was not present in prior versions.

**Comment by paddyobrien** [comment]
Oh also, should these be [BUGFIX release], I found this while working on a 1.12 upgrade and this behaviour would prevent me from continuing that upgrade.

**Comment by rwjblue** [comment]
`[BUGFIX release]` seems fine, we have a handful of other changes for 1.12.1 also.

**Comment by paddyobrien** [comment]
ok, updated to `[BUGFIX release]`

**Comment by stefanpenner** [comment]
> Short version: yes, it is a regression in 1.12 that was not present in prior versions.

:+1:

**Comment by rwjblue** [comment]
@paddyobrien - Thank you!
