### PR TITLE
[BUGFIX release] Fix descriptorFor to support fallback

### LINKED ISSUE #16427: [3.1.0-beta.5] notifyPropertyChange() fails for plain objects
This unit test will fail on the latest beta:

```js
test('notifies computed properties on plain objects', function (assert) {
  let obj = {
    a: 45,
    b: computed(function () {
      return ~~(this.a / 10);
    })
  };

  assert.equal(get(obj, 'b'), 4);

  obj.a = 10;
  Ember.notifyPropertyChange(obj, 'b');

  assert.equal(get(obj, 'b'), 1);      // fails - returned value is still 4
});
```

It works, as intended, if I do the same on an ember object.

### PR DESCRIPTION
**Pull request by krisselden**
Ensure all fallback cases are deprecated.

Fixes #16427 and add test for `notifyPropertyChange` not working for plain obj.

### CODE REVIEW

File: packages/ember-metal/lib/property_set.js [hunk 1]
```diff
@@ -78,10 +78,39 @@ export function set(obj, keyName, value, tolerant) {
...
+      },
+    });
+
+    meta(obj).writeDescriptors(keyName, currentValue);
+
+    if (typeof currentValue.setup === 'function') {
+      currentValue.setup(obj, keyName);
+    }
+
+    return currentValue.get(obj, keyName);
```
Comment (rwjblue) [inline packages/ember-metal/lib/property_set.js]: Don’t we want to call `currentValue.set(obj, keyName, value)`? Why would we call `.get`?

**Review by rwjblue — COMMENTED** [review]
We should add tests for the deprecated things. Adding a CP as a property on a POJO or something, then calling get, confirm the deprecation, confirm that we can updated a dep key and have the CP recompute, etc (same for set first).

**Review by rwjblue — APPROVED** [review]
