### PR TITLE
[BUGFIX beta] Fix input macro params handling

### LINKED ISSUE #16256: Input helper passed type does not work in Ember 3.1 beta
I was working on updating my apps and addons to 3.1 beta and noticed some strange behavior. I have components that wrap the `{{input}}` helper and only the first one was rendering an input. I created a reproduction here https://github.com/rwwagner90/inputs and I played around with it some. It appears the issue is passing `type` down as an argument. It chokes on:

```hbs
{{input type=type}}
```

I also tested this against https://s3.amazonaws.com/builds.emberjs.com/canary/shas/9300d1b7d3aa70987986b1997ecf02a542ea49be.tgz and there did not seem to be any difference.

### PR DESCRIPTION
**Pull request by Serabe**
Before this PR, having a component with an `{{input}}` with bound type
would make that input only to work the first time it was rendered. This
was because the first param would be shifter from params, and that would
modify the params of the rest of the instances.

This is breaking in current beta.

Fixes #16256

### CODE REVIEW

File: packages/ember-glimmer/tests/integration/helpers/input-test.js [hunk 1]
```diff
@@ -446,6 +446,22 @@ moduleFor('Helpers test: {{input}} with dynamic type', class extends InputRender
 
     this.assertAttr('type', 'text');
   }
+
+  ['@test GH16256 input macro does not modify params in palce']() {
```
Comment (andyhot) [inline packages/ember-glimmer/tests/integration/helpers/input-test.js]: typo for place

Comment (Serabe) [reply packages/ember-glimmer/tests/integration/helpers/input-test.js]: Done. Thank you!

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Awesome sleuthing! Thank you!
