### PR TITLE
[BUGFIX beta] Pass resolver to Test app in generated initializer test

### LINKED ISSUE #19046: [Bug] Default initializer test shows globals-resolver deprecation
### 🐞 Describe the Bug
Initializer tests logs deprecation warning for usage of `globals-resolver`.

### 🔬 Minimal Reproduction

```bash
ember new
ember g initializer foo
ember test --filter="initializer"
```

### 😕 Actual Behavior
A deprecation warning is logged

### 🤔 Expected Behavior
No deprecation should be logged for code the user has not written

### 🌍 Environment

- Ember: - 3.18 (pretty sure same behavior in later build too)

### ➕ Additional Context

The problem is that `Application.create()` is called with only the `autoboot: false` properties:

https://github.com/emberjs/ember.js/blob/v3.20.1/blueprints/initializer-test/qunit-rfc-232-files/__root__/__testType__/__path__/__name__-test.js#L15

Since a `Resolver` from ember-resolver is not passed, the DefaultResolver is used, which is the globals resolver. 

Either the default should change, or the right Resolver can be imported and passed into the test application in the blueprint.

### PR DESCRIPTION
**Pull request by mehulkar**
The default resolver (the globals resolver is deprecated), so we
always need to pass this in.

Closes #19046

### CODE REVIEW

File: node-tests/fixtures/initializer-test/rfc232.js [hunk 1]
```diff
@@ -3,16 +3,17 @@ import Application from '@ember/application';
 import { initialize } from 'my-app/initializers/foo';
 import { module, test } from 'qunit';
 import { run } from '@ember/runloop';
+import Resolver from 'ember-resolver';
 
 module('Unit | Initializer | foo', function(hooks) {
   hooks.beforeEach(function() {
-    this.TestApplication = Application.extend();
+    this.TestApplication = class TestApplication extends Appication {}
```
Comment (rwjblue) [inline node-tests/fixtures/initializer-test/rfc232.js:10]:
```suggestion
    this.TestApplication = class TestApplication extends Application {}
```

File: node-tests/fixtures/instance-initializer-test/rfc232.js [hunk 2]
```diff
@@ -3,15 +3,16 @@ import Application from '@ember/application';
 import { initialize } from 'my-app/instance-initializers/foo';
 import { module, test } from 'qunit';
 import { run } from '@ember/runloop';
+import Resolver from 'ember-resolver';
 
 module('Unit | Instance Initializer | foo', function(hooks) {
   hooks.beforeEach(function() {
-    this.TestApplication = Application.extend();
+    this.TestApplication = class TestApplication extends Appication {}
```
Comment (rwjblue) [inline node-tests/fixtures/instance-initializer-test/rfc232.js:10]:
```suggestion
    this.TestApplication = class TestApplication extends Application {}
```

**Review by rwjblue — CHANGES_REQUESTED** [review]

File: node-tests/fixtures/initializer-test/module-unification/rfc232.js [hunk 3]
```diff
@@ -2,17 +2,18 @@ import Application from '@ember/application';
 
 import { initialize } from 'my-app/init/initializers/foo';
 import { module, test } from 'qunit';
+import Resolver from 'ember-resolver';
 import { run } from '@ember/runloop';
 
 module('Unit | Initializer | foo', function(hooks) {
   hooks.beforeEach(function() {
-    this.TestApplication = Application.extend();
+    this.TestApplication = class TestApplication extends Appication {}
```
Comment (rwjblue) [inline node-tests/fixtures/initializer-test/module-unification/rfc232.js:10]:
```suggestion
    this.TestApplication = class TestApplication extends Application {}
```

File: node-tests/fixtures/instance-initializer-test/module-unification/rfc232.js [hunk 4]
```diff
@@ -2,16 +2,17 @@ import Application from '@ember/application';
 
 import { initialize } from 'my-app/init/instance-initializers/foo';
 import { module, test } from 'qunit';
+import Resolver from 'ember-resolver';
 import { run } from '@ember/runloop';
 
 module('Unit | Instance Initializer | foo', function(hooks) {
   hooks.beforeEach(function() {
-    this.TestApplication = Application.extend();
+    this.TestApplication = class TestApplication extends Appication {}
```
Comment (rwjblue) [inline node-tests/fixtures/instance-initializer-test/module-unification/rfc232.js:10]:
```suggestion
    this.TestApplication = class TestApplication extends Application {}
```

File: node-tests/fixtures/initializer-test/module-unification/rfc232.js (hunk 3 above)
Comment (mehulkar) [reply node-tests/fixtures/initializer-test/module-unification/rfc232.js:10]: wow, that was so sloppy, sorry rob.

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Awesome, thanks for working on this!
