### PR TITLE
[BUGFIX beta] Ensure that calling `wait` without routing works.

### LINKED ISSUE #10263: `router` is undefined in wait() test helper
When using this [authenticateSession](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-testing/lib/simple-auth-testing/test-helpers.js#L4) test helper, my test suite crashes.

The crash happens inside the `wait()` method of `ember-testing/lib/helpers.js`, where `lookup('router:main').router` returns undefined on this line: https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers.js#L211

My acceptance test is very basic:

```coffeescript
`import Ember from 'ember'`
`import startApp from '../helpers/start-app'`

App = null

module 'Acceptance: Login',
  setup: ->
    App = startApp()

  teardown: ->
    Ember.run App, 'destroy'

test 'It redirects if already logged in', ->
  authenticateSession()
  visit '/login'

  andThen ->
    equal currentPath(), '/'
```

If I remove the `authenticateSession()` call then the test runs without issue.

Are there any known conditions that may cause `router` to be undefined? Is there anything I can do to get further information for debugging?

> Ember: 1.11.0-beta.1+canary.8ca36b56
> Ember Data: 1.0.0-beta.14.1
> jQuery: 1.11.2
> Ember Simple Auth: 0.7.2
> Ember Simple Auth Devise: 0.7.2

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #10263.

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM

File: packages/ember-testing/lib/helpers.js [hunk 1]
```diff
@@ -207,8 +207,10 @@ function wait(app, value) {
 
     // Every 10ms, poll for the async thing to have finished
     var watcher = setInterval(function() {
+      var router = app.__container__.lookup('router:main');
+
       // 1. If the router is loading, keep polling
-      var routerIsLoading = !!app.__container__.lookup('router:main').router.activeTransition;
+      var routerIsLoading = router.router && !!router.router.activeTransition;
```
Comment (stefanpenner) [inline packages/ember-testing/lib/helpers.js]: it is unfortunate that this may happen before routing even starts, is it possible for this code to wait atleast for routing to begin?

Comment (stefanpenner) [inline packages/ember-testing/lib/helpers.js]: at the very least post initializers running

(that being said this is still better then the existing, so i am fine with merging without fixing ^^)

Comment (rwjblue) [inline packages/ember-testing/lib/helpers.js]: I agree.  This PR is mostly just to prevent the whole thing from blowing up when routing isn't started (when `visit` is called).

Comment (stefanpenner) [inline packages/ember-testing/lib/helpers.js]: :+1: 

mind opening another issue for the second concern? (if you think it is worth while)

Comment (rwjblue) [inline packages/ember-testing/lib/helpers.js]: Discussed this with @wycats a bit in chat, and your second issue will be resolved by work he has underway.
