### PR TITLE
[BUGFIX] Handle binding namespaced attributes (#9298)

### LINKED ISSUE #9298: Ember.Component attributeBindings doesn't work with namespaced attributes? (e.g. xlink:href)
The following code produces undesired results:

```js
export default Ember.Component.extend({
  tagName: 'image',

  attributeBindings: ['src:xlink:href', 'x', 'y', 'width', 'height'],

  src: '/mericuh-flag.gif'
});
```

It ends up setting `xlink="/mericuh-flag.gif"` rather than `xlink:href="/mericuh-flag.gif"`

Suggested workaround from @ebryn was to use an observer and manually set, which I'm fine with for now.

### PR DESCRIPTION
**Pull request by oneeman**
Resolves https://github.com/emberjs/ember.js/issues/9298 as proposed in https://github.com/emberjs/ember.js/pull/10186#discussion_r22911832.

### CODE REVIEW

**Comment by rwjblue** [comment]
Small clarification, this cannot be pulled into beta (since #10186 is only on master).  Can you remove the `[BUGFIX beta]` prefix (or explain if I am missing something obvious)?

**Comment by oneeman** [comment]
No, I'm the one who was missing something.  Will do.

File: packages/ember-views/tests/views/view/attribute_bindings_test.js [hunk 1]
```diff
@@ -193,6 +193,22 @@ QUnit.test("should update attribute bindings with micro syntax", function() {
...
+
+  run(function() {
+    view.createElement();
+  });
+  equal(view.$().attr('xlink:href'), '/foo.png', "namespaced attribute is set");
+
+  run(function () {
+    view.set('xlinkHref', '/bar.png');
+  });
+  equal(view.$().attr('xlink:href'), '/bar.png', "namespaced attribute is updated");
```
Comment (mixonic) [inline packages/ember-views/tests/views/view/attribute_bindings_test.js]: Does this pass in IE8?

**Comment by mixonic** [comment]
@rwjblue I'd also like to land this into 1.11!

File: packages/ember-views/tests/views/view/attribute_bindings_test.js (hunk 1 above)
Comment (oneeman) [inline packages/ember-views/tests/views/view/attribute_bindings_test.js]: Don't know.  Was going to try it out with an interactive saucelabs session just now, but both it and master stop with 0 of 3 assertions passed: http://imgur.com/rP5PVTA.  I can try on a VM tonight to see what's going on.

Comment (rwjblue) [inline packages/ember-views/tests/views/view/attribute_bindings_test.js]: We do something like the following in HTMLBars for `setAttributeNS` detection:

```javascript
var doc = typeof document === 'undefined' ? false : document;
if (doc && doc.createElementNS) { 
  /* do stuff */
}
```

That might work here?

Comment (oneeman) [inline packages/ember-views/tests/views/view/attribute_bindings_test.js]: So I was using `npm start` instead of `ember serve --environment=production`.  Did it again using the latter and all the tests in the module (including the one I added) pass in IE8.

Comment (rwjblue) [inline packages/ember-views/tests/views/view/attribute_bindings_test.js]: Good enough for me, thank you!
