### PR TITLE
[BUGFIX release] Remove Unnecessary Override of emptyViewclass in Each Helper

### LINKED ISSUE #10019: {{each}}'s emptyView Broken in 1.9?
I think `{{#each}}`'s `emptyViewClass` argument is broken. Sample JSBin http://emberjs.jsbin.com/galivadoja/2/. This was working just fine and dandy in 1.8.1 using both the `emptyView` and `emptyViewClass` arguments.

### PR DESCRIPTION
**Pull request by jherdman**
Overriding the `emptyViewClass` in the each helper is breaking usage of
the {{#each}} helper when used as follows:

``` handlebars
{{each person in people emptyView='myEmptyView'}}
```

Fixes #10019

HT @mmun for all of the help!

### CODE REVIEW

File: packages/ember-htmlbars/tests/helpers/each_test.js [hunk 1]
```diff
@@ -607,6 +612,127 @@ test("it supports {{itemViewClass=}} with in format", function() {
 
 });
 
+test("it supports {{emptyView=}}", function() {
```
Comment (jherdman) [inline packages/ember-htmlbars/tests/helpers/each_test.js]: Still failing... I could use some help on this one. The problem seems to be that the below `view` can't find its container when the parent view is creating it the empty view instance ([see here](https://github.com/emberjs/ember.js/blob/d1d5578cbefda479851db99074ab959671351794/packages/ember-views/lib/views/view.js#L1924-L1930)).

If I tweak the below view (see below), it fails deeper when its attempting to append to the document:

```javascript
view = EmberView.create({
  template: templateFor('{{each view.people emptyView="anEmptyView"}}'),
  people: A(),
  container: container
});
```

Ping @mmun

Comment (mmun) [inline packages/ember-htmlbars/tests/helpers/each_test.js]: @jherdman Assigning the container to the view makes a lot more sense then assigning it to the controller (The only place this make sense is on the one test that looks up an item controller).

I made the changes and everything was passing.

Comment (jherdman) [inline packages/ember-htmlbars/tests/helpers/each_test.js]: @mmun hmm okay. I'm a bit confused as to why the [itemView](https://github.com/emberjs/ember.js/blob/d1d5578cbefda479851db99074ab959671351794/packages/ember-htmlbars/tests/helpers/each_test.js#L490-L509) test is passing then. Any thoughts?

**Comment by mmun** [comment]
@jherdman Looks good. Couple points:

- Please prefix the commit with `[BUGFIX release]` because it will be going in all 3 channels.
- Please modify the itemView tests in a similar way (hoist the container to the view, remove it from the controller) [here](https://github.com/jherdman/ember.js/blob/empty-view-tests/packages/ember-htmlbars/tests/helpers/each_test.js#L504-L506) and [here](https://github.com/jherdman/ember.js/blob/empty-view-tests/packages/ember-htmlbars/tests/helpers/each_test.js#L526-L528).

**Comment by jherdman** [comment]
Done!

**Comment by mmun** [comment]
Woo hoo! Thanks a lot.
