### PR TITLE
[BUGFIX beta] Fix positional params in contextual components with dot syntax

### LINKED ISSUE #12625: Positional params issue in contextual components
An assertion is being triggered when attempting to use positional params with contextual components via the hash helper.

Imagine the following

```hbs
{{!-- templates/components/parent-component.hbs --}}
{{yield (hash childComponent=(component "child-component"))}}
```

```js
// components/child-component.js
import Ember from 'ember';

const childComponent = Ember.Component.extend({});

childComponent.reopenClass({
  positionalParams: "params"
});

export default childComponent;
```

If we attempt to instantiate `childComponent` directly, the assertion is triggered, if we instantiate `childComponent` using the component helper, everything works as expected. See below for examples:

```hbs
{{!-- Not Working --}}
{{#parent-component as |hash|}}
  {{hash.childComponent "param1" "param2"}}
{{/parent-component}}

{{!-- Working --}}
{{#parent-component as |hash|}}
  {{component hash.childComponent "param1" "param2"}}
{{/parent-component}}
```

I've also created a couple of Twiddles, one showing the error and one showing it working when used with the component helper.

**Working:**
https://ember-twiddle.com/331b165b525660a2307d

**Not Working:**
https://ember-twiddle.com/cef32d9fc97b265e824b

The assertion being thrown is:
```
Uncaught Error: Assertion Failed: You cannot specify positional parameters and the hash argument `params`.
```

I discovered the issue on v2.3.0-beta.1 although I suspect the issue could also affect v2.2.0.

### PR DESCRIPTION
**Pull request by Serabe**
As reported in #12625, positional parameters were not being rendered correctly
when using the dot syntax. A longer description on the cause of the problem has
been added as a comment to `ember-htmlbars/lib/hooks/component.js` for future
warning.

Fix #12625

### CODE REVIEW

**Comment by rwjblue** [comment]
LGTM

@mixonic - r?

**Comment by Serabe** [comment]
Sauce is failing :(

**Comment by rwjblue** [comment]
Restarted it.

File: packages/ember-htmlbars/lib/node-managers/component-node-manager.js [hunk 1]
```diff
@@ -59,8 +59,7 @@ ComponentNodeManager.create = function ComponentNodeManager_create(renderNode, e
   configureCreateOptions(attrs, createOptions);
 
   // If there is a controller on the scope, pluck it off and save it on the
-  // component. This allows the component to target actions sent via
-  // `sendAction` correctly.
+  // component. This allows the component to target actions sent via // `sendAction` correctly.
```
Comment (mixonic) [inline packages/ember-htmlbars/lib/node-managers/component-node-manager.js]: lost a newline here

Comment (Serabe) [inline packages/ember-htmlbars/lib/node-managers/component-node-manager.js]: Fixed!

File: packages/ember-htmlbars/lib/hooks/component.js [hunk 2]
```diff
@@ -33,6 +34,29 @@ export default function componentHook(renderNode, env, scope, _tagName, params,
     let componentCell = stream.value();
     if (isComponentCell(componentCell)) {
       tagName = componentCell[COMPONENT_PATH];
+
+      /*
+       * This need to be done to avoid problems with rest positional parameters
```
Comment (mixonic) [inline packages/ember-htmlbars/lib/hooks/component.js]: > This need to be done to avoid

into

> Processing positional params before merging into a hash must be done here to avoid

File: packages/ember-htmlbars/lib/hooks/component.js [hunk 3]
```diff
@@ -33,6 +34,29 @@ export default function componentHook(renderNode, env, scope, _tagName, params,
...
+       * when rendered using the dot notation.
```
Comment (mixonic) [inline packages/ember-htmlbars/lib/hooks/component.js]: ~~when~~

File: packages/ember-htmlbars/lib/hooks/component.js [hunk 4]
```diff
@@ -33,6 +34,29 @@ export default function componentHook(renderNode, env, scope, _tagName, params,
...
+       *
+       * Closure components (for the contextual component feature) does not
```
Comment (mixonic) [inline packages/ember-htmlbars/lib/hooks/component.js]: "does not" -> "do not"

File: packages/ember-htmlbars/lib/hooks/component.js [hunk 5]
```diff
@@ -33,6 +34,29 @@ export default function componentHook(renderNode, env, scope, _tagName, params,
...
+       * actually keep the positional params, but process them at each level.
+       * Therefore, when rendering a closure component with the component
+       * helper we just process the parameters and attributes and then we
```
Comment (mixonic) [inline packages/ember-htmlbars/lib/hooks/component.js]: "we process the parameters and attributes and then merge those on top of the closure component attributes"

File: packages/ember-htmlbars/lib/hooks/component.js [hunk 6]
```diff
@@ -33,6 +34,29 @@ export default function componentHook(renderNode, env, scope, _tagName, params,
...
+       * merged on top of the closure component attributes.
+       *
+       * In the dot syntax rendering case, it was being doing just by merging
+       * the new attributes with the closure component's and then letting the
+       * rendering process the positional parameters. This caused a problem
+       * with because the new attributes already contain an entry for the rest
+       * positional parameters.
```
Comment (mixonic) [inline packages/ember-htmlbars/lib/hooks/component.js]: I'd drop this paragraph as it describes a problem that no longer exists.

File: packages/ember-htmlbars/lib/hooks/component.js [hunk 7]
```diff
@@ -33,6 +34,29 @@ export default function componentHook(renderNode, env, scope, _tagName, params,
...
+       *
+       * This is the reason that positional parameters need to be processed
+       * with attributes and then merged with the previous coming from the
+       * closure component.
```
Comment (mixonic) [inline packages/ember-htmlbars/lib/hooks/component.js]: And this :-) IMO the first two paragraphs are good enough for code, the rest might be good in the issue description here but that is all.

**Comment by mixonic** [comment]
Seems good pending small doc edits :-)

**Comment by Serabe** [comment]
@mixonic I think I've addressed them all

**Comment by rwjblue** [comment]
Restarted Sauce

**Comment by mixonic** [comment]
thanks @Serabe !

**Comment by Serabe** [comment]
:+1:
