### PR TITLE
[BUGFIX release] Correct types for Ember Arrays

### LINKED ISSUE #20230: [Preview Types Bug] `map` on an `EmberArray` returns `EmberArray` but shouldn't
### 🐞 Describe the Bug
This applies for the preview-types from Ember 4.8.0.

### 🔬 Minimal Reproduction
```ts
const x: NativeArray<string> = A();
const y = x.map(z => z);
```

### 😕 Actual Behavior
`y` is typed as `NativeArray`.

### 🤔 Expected Behavior
`y` is typed as `Array`.

Note that this is true at runtime only for modern browsers. For old browsers, the current types are correct... see [here](https://github.com/emberjs/ember.js/blob/v4.8.0/packages/@ember/array/index.ts#L1941). In modern browsers, `map` comes from the browser. It returns a native JS array. Otherwise an Ember version of [map](https://github.com/emberjs/ember.js/blob/v4.8.0/packages/@ember/array/index.ts#L721) is used which actually returns an `EmberArray`. I believe that should be fixed and the types should be changed to return native JS arrays.

Same applies for `mapBy` (which uses `map`), `filter`, `filterBy` and perhaps others.

### 🌍 Environment

- Ember: - 4.8.0

cc @chriskrycho, @wagenet

### PR DESCRIPTION
**Pull request by wagenet**
This PR does a couple of things to improve array types:
* More fully unifies internal array types with external preview types.
* Corrects NativeArray types to not override methods from the true native JS array.

Fixes #20230

### CODE REVIEW

**Comment by chriskrycho** [comment]
Top-level request (I'll review further later): can you add an explanation to the PR so we can refer to it later to understand *why* these specific changes are correct?

File: packages/@ember/-internals/utils/types.ts [hunk 1]
```diff
@@ -1,7 +1,15 @@
 export type AnyFn = (...args: any[]) => any;
 
+export type MethodsOf<O> = {
+  [K in keyof O]: O[K] extends AnyFn ? O[K] : never;
+};
```
Comment (chriskrycho) [inline packages/@ember/-internals/utils/types.ts:5]: This doesn't actually work, unfortunately. You need something like the final `keyof` as used in `MethodNamesOf` below to make it properly strip out the bits which are actually `never`. It turns out the easiest way to get `MethodsOf` is to reuse `MethodNamesOf` in conjunction with `Pick`:

```ts
type MethodsOf<O> = Pick<O, MethodNamesOf<O>>;
```

[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggdiAYnKBeKAKAdDghgJwHMBnALilwQG0BdASjQD4KEBuAKHYgA8wB7fMCihIUALIRgACz4ATYgHkAZgB4FzdAG92UKFQDSUAJYoA1hBB8lUBTXIKDNKD2AQ482AmRQA-DcdQ5HAQAG4Q+BwAvhzsItAAQpKu+BLScoqq6mhQAApGAMamagA04pIysgByuAC2EBlqjIwxPPyCwuDQqRXVdQ0AKhpQ2rp6hiZQ5pbW-XZQ-QEubh7wSCh+hkGh4RxQkVRTVvM0MQD0p1AAVgCuxELEfFCW11D5lFDEENAyAO7GQj8BKZiFAfkZpMIpNAeLUwAAbepQABGEDhfB+7FkEHycII0BxuGIILEuBAKJUg2GOlGIVwcOuEB85H6u1GNVwYBUAFVGBglHByBhgMyGKhmFy6OQSWSINzmuxIpw4lAABrZbpyXr1ZQqaXk65wUxwdFwJocZUATXV5XSOr1soNRpNZtinSgAC1solgMkNfI7aT9YbjT9Tc0gA)

File: types/preview/@ember/array/mutable.d.ts [hunk 2]
```diff
@@ -15,7 +15,7 @@ declare module '@ember/array/mutable' {
     /**
      * __Required.__ You must implement this method to apply this mixin.
      */
-    replace(idx: number, amt: number, objects: T[]): this;
+    replace(idx: number, amt: number, objects: T[]): void;
```
Comment (wagenet) [inline types/preview/@ember/array/mutable.d.ts:18]: In some cases we do return `this`, but the docs state that we do not return.

File: packages/@ember/array/index.ts [hunk 3]
```diff
@@ -515,7 +519,8 @@ interface EmberArray<T> extends Enumerable {
     @return {Array} The mapped array.
     @public
   */
-  getEach<K extends string>(key: K): NativeArray<Value<T, K>>;
+  getEach<K extends keyof T>(key: K): NativeArray<T[K]>;
+  getEach<K extends CompoundPropertyKey<T>>(key: K): NativeArray<unknown>;
```
Comment (chriskrycho) [inline packages/@ember/array/index.ts:523]: Instead of introducing additional type shenanigans here, since it ultimately just becomes `NativeArray<unknown>`, we can just use `string`. (This is how we do it with the overloads in Ember and Ember Data).

```suggestion
  getEach(key: string): NativeArray<unknown>;
```

File: packages/@ember/array/index.ts [hunk 4]
```diff
@@ -20,12 +20,15 @@ import MutableEnumerable from '@ember/enumerable/mutable';
...
+import type { MethodNamesOf, MethodParams, MethodReturns } from '@ember/-internals/utils/types';
 import type { ComputedPropertyCallback } from '@ember/-internals/metal';
 
 export { makeArray } from '@ember/-internals/utils';
 
-type Value<T, K extends string> = K extends keyof T ? T[K] : unknown;
+export type EmberArrayLike<T> = EmberArray<T> | NativeArray<T>;
+
+// We don't currently attempt to fully type-check compound keys
+type CompoundPropertyKey<T> = `${keyof T & string}.${string}`;
```
Comment (chriskrycho) [inline packages/@ember/array/index.ts:31]: Then we don't need this!

```suggestion
```

File: packages/@ember/array/index.ts [hunk 5]
```diff
@@ -746,10 +752,6 @@ interface EmberArray<T> extends Enumerable {
     @public
   */
   rejectBy(key: string, value?: unknown): NativeArray<T>;
-  find<S extends T, Target = void>(
-    predicate: (this: void, value: T, index: number, obj: T[]) => value is S,
-    thisArg?: Target
-  ): S | undefined;
```
Comment (wagenet) [inline packages/@ember/array/index.ts:752]: Just moved this.

File: packages/@ember/array/index.ts [hunk 6]
```diff
@@ -1061,10 +1070,10 @@ interface EmberArray<T> extends Enumerable {
...
     @public
   */
-  invoke<K extends string>(
-    methodName: K,
-    ...args: Value<T, K> extends AnyFn ? Parameters<Value<T, K>> : unknown[]
-  ): NativeArray<Value<T, K> extends AnyFn ? ReturnType<Value<T, K>> : unknown>;
+  invoke<M extends MethodNamesOf<T>>(
+    methodName: M,
+    ...args: MethodParams<T, M>
+  ): NativeArray<MethodReturns<T, M>>;
```
Comment (wagenet) [inline packages/@ember/array/index.ts:1076]: The public preview types were better here.

File: packages/@ember/array/index.ts [hunk 7]
```diff
@@ -1086,7 +1095,7 @@ interface EmberArray<T> extends Enumerable {
     @return {Array} the array without null and undefined elements.
     @public
   */
-  compact(): NativeArray<Exclude<T, null>>;
+  compact(): NativeArray<NonNullable<T>>;
```
Comment (wagenet) [inline packages/@ember/array/index.ts:1098]: The public preview types were better here.

File: packages/@ember/array/index.ts [hunk 8]
```diff
@@ -1176,6 +1185,7 @@ interface EmberArray<T> extends Enumerable {
     @public
   */
   uniqBy(key: string): NativeArray<T>;
+  uniqBy(callback: (value: T) => unknown): NativeArray<T>;
```
Comment (wagenet) [inline packages/@ember/array/index.ts:1188]: This was missing before.

File: packages/@ember/array/index.ts [hunk 9]
```diff
@@ -1632,7 +1642,7 @@ interface MutableArray<T> extends EmberArray<T>, MutableEnumerable {
     @return object same object passed as a param
     @public
   */
-  unshiftObject(object: T): this;
+  unshiftObject(object: T): T;
```
Comment (wagenet) [inline packages/@ember/array/index.ts:1645]: This was incorrect before.

File: packages/@ember/array/index.ts [hunk 10]
```diff
@@ -1892,6 +1902,167 @@ const MutableArray = Mixin.create(EmberArray, MutableEnumerable, {
...
+  | 'setObjects'
+  | 'removeObject'
+  | 'removeObjects'
+  | 'addObject'
+  | 'addObjects'
+  | 'setEach';
+
+// This is the same as MutableArray, but removes the actual native methods that exist on Array.prototype.
+interface MutableArrayWithoutNative<T>
+  extends Omit<MutableArray<T>, IGNORED_MUTABLE_ARRAY_METHODS | RETURN_SELF_ARRAY_METHODS> {
```
Comment (wagenet) [inline packages/@ember/array/index.ts:1946]: NativeArray is MutableArray with all actual native methods removed. Unfortunately, because of how Omit works, all methods that return `this` will end up not returning the correct `this`, so we also have to redefine those methods here.

File: packages/@ember/array/type-tests/index.ts [hunk 11]
```diff
@@ -37,9 +40,9 @@ expectTypeOf(arr.firstObject).toEqualTypeOf<Foo | undefined>();
 
 expectTypeOf(arr.lastObject).toEqualTypeOf<Foo | undefined>();
 
-expectTypeOf(arr.slice()).toEqualTypeOf<NativeArray<Foo>>();
-expectTypeOf(arr.slice(1)).toEqualTypeOf<NativeArray<Foo>>();
-expectTypeOf(arr.slice(1, 2)).toEqualTypeOf<NativeArray<Foo>>();
+expectTypeOf(arr.slice()).toEqualTypeOf<Foo[]>();
+expectTypeOf(arr.slice(1)).toEqualTypeOf<Foo[]>();
+expectTypeOf(arr.slice(1, 2)).toEqualTypeOf<Foo[]>();
```
Comment (wagenet) [inline packages/@ember/array/type-tests/index.ts:45]: We're actually hitting the native slice.

File: packages/@ember/array/type-tests/index.ts [hunk 12]
```diff
@@ -49,7 +52,7 @@ expectTypeOf(arr.lastIndexOf(new Foo())).toEqualTypeOf<number>();
 // @ts-expect-error checks param type
 arr.lastIndexOf('invalid');
 
-expectTypeOf(arr.forEach((item: Foo) => String(item))).toEqualTypeOf(arr);
+expectTypeOf(arr.forEach((item: Foo) => String(item))).toEqualTypeOf<void>();
```
Comment (wagenet) [inline packages/@ember/array/type-tests/index.ts:55]: Native forEach returns void.

File: packages/@ember/array/type-tests/index.ts [hunk 13]
```diff
@@ -58,43 +61,44 @@ arr.forEach((item, index, arr) => {
   expectTypeOf(arr).toEqualTypeOf(arr);
 });
 arr.forEach(function (_item) {
-  expectTypeOf(this).toEqualTypeOf(target);
```
Comment (wagenet) [inline packages/@ember/array/type-tests/index.ts:61]: Native methods behave differently here.

File: packages/@ember/array/type-tests/index.ts [hunk 14]
```diff
@@ -58,43 +61,44 @@ arr.forEach((item, index, arr) => {
...
+  // No-op
 }, target);
 
 expectTypeOf(arr.getEach('bar')).toEqualTypeOf<NativeArray<number>>();
-expectTypeOf(arr.getEach('missing')).toEqualTypeOf<NativeArray<unknown>>();
+// @ts-expect-error property is unknown
+arr.getEach('missing');
```
Comment (wagenet) [inline packages/@ember/array/type-tests/index.ts:69]: We updated types to not allow this case.

File: packages/@ember/array/type-tests/index.ts [hunk 15]
```diff
@@ -58,43 +61,44 @@ arr.forEach((item, index, arr) => {
...
 
 expectTypeOf(arr.setEach('bar', 2)).toEqualTypeOf(arr);
 // @ts-expect-error string is not assignable to bar
 arr.setEach('bar', 'string');
 
-// Can set unknown property
-expectTypeOf(arr.setEach('missing', 'anything')).toEqualTypeOf(arr);
+// @ts-expect-error property is unknown
+arr.setEach('missing', 'anything');
```
Comment (wagenet) [inline packages/@ember/array/type-tests/index.ts:76]: We updated types to not allow this.

File: packages/@ember/array/type-tests/index.ts [hunk 16]
```diff
@@ -166,16 +172,14 @@ let reduced = arr.reduce((summation, item, index, arr) => {
   return 1;
 }, 1);
 expectTypeOf(reduced).toEqualTypeOf<number>();
-// NOTE: This doesn't match native behavior and is a bit weird
-expectTypeOf(arr.reduce((summation, _item) => summation)).toEqualTypeOf<unknown>();
+expectTypeOf(arr.reduce((summation, _item) => summation)).toEqualTypeOf<Foo>();
```
Comment (wagenet) [inline packages/@ember/array/type-tests/index.ts:175]: This does match native types now.

File: packages/@ember/array/type-tests/mutable.ts [hunk 17]
```diff
@@ -1,63 +1,67 @@
-import type MutableArray from '@ember/array/mutable';
-import { A } from '@ember/array';
+import MutableArray from '@ember/array/mutable';
 
 import { expectTypeOf } from 'expect-type';
 
-class Foo {}
+class Foo {
+  constructor(public name: string) {}
```
Comment (wagenet) [inline packages/@ember/array/type-tests/mutable.ts:6]: This needed a property for the checks below to fully work.

File: packages/@ember/array/index.ts [hunk 18]
```diff
@@ -593,7 +598,8 @@ interface EmberArray<T> extends Enumerable {
     @return {Array} The mapped array.
     @public
   */
-  mapBy<K extends string>(key: K): NativeArray<Value<T, K>>;
+  mapBy<K extends keyof T>(key: K): NativeArray<T[K]>;
+  mapBy<K extends CompoundPropertyKey<T>>(key: K): NativeArray<unknown>;
```
Comment (chriskrycho) [inline packages/@ember/array/index.ts:602]:
```suggestion
  mapBy(key: string): NativeArray<unknown>;
```

File: packages/@ember/array/index.ts [hunk 19]
```diff
@@ -824,7 +830,8 @@ interface EmberArray<T> extends Enumerable {
     @return {Object} found item or `undefined`
     @public
   */
-  findBy<K extends string>(key: K, value?: Value<T, K>): T | undefined;
+  findBy<K extends keyof T>(key: K, value?: T[K]): T | undefined;
+  findBy<K extends CompoundPropertyKey<T>>(key: K, value?: unknown): T | undefined;
```
Comment (chriskrycho) [inline packages/@ember/array/index.ts:834]:
```suggestion
  findBy(key: string, value?: unknown): T | undefined;
```

File: packages/@ember/array/index.ts [hunk 20]
```diff
@@ -904,7 +911,8 @@ interface EmberArray<T> extends Enumerable {
     @since 1.3.0
     @public
   */
-  isEvery<K extends string>(key: K, value?: Value<T, K>): boolean;
+  isEvery<K extends keyof T>(key: K, value?: T[K]): boolean;
+  isEvery<K extends CompoundPropertyKey<T>>(key: K, value?: unknown): boolean;
```
Comment (chriskrycho) [inline packages/@ember/array/index.ts:915]:
```suggestion
  isEvery(key: string, value?: unknown): boolean;
```

File: packages/@ember/array/index.ts [hunk 21]
```diff
@@ -972,7 +980,8 @@ interface EmberArray<T> extends Enumerable {
     @since 1.3.0
     @public
   */
-  isAny<K extends string>(key: K, value?: Value<T, K>): boolean;
+  isAny<K extends keyof T>(key: K, value?: T[K]): boolean;
+  isAny<K extends CompoundPropertyKey<T>>(key: K, value?: unknown): boolean;
```
Comment (chriskrycho) [inline packages/@ember/array/index.ts:984]:
```suggestion
  isAny(key: string, value?: unknown): boolean;
```

File: packages/@ember/debug/container-debug-adapter.ts [hunk 22]
```diff
@@ -88,9 +88,9 @@ export default class ContainerDebugAdapter extends EmberObject {
     @return {Array} An array of strings.
     @public
   */
-  catalogEntriesByType(type: string): NativeArray<string> {
-    let namespaces = emberA(Namespace.NAMESPACES);
-    let types = emberA<string>();
+  catalogEntriesByType(type: string): string[] {
+    let namespaces = Namespace.NAMESPACES;
+    let types: string[] = [];
```
Comment (wagenet) [inline packages/@ember/debug/container-debug-adapter.ts:93]: This is just documented as returning an array.

File: packages/@ember/debug/data-adapter.ts [hunk 23]
```diff
@@ -544,22 +544,22 @@ export default class DataAdapter<T> extends EmberObject {
...
+  getModelTypes(): Array<{ klass: unknown; name: string }> {
     let containerDebugAdapter = this.containerDebugAdapter;
 
     let stringTypes = containerDebugAdapter.canCatalogEntriesByType('model')
       ? containerDebugAdapter.catalogEntriesByType('model')
       : this._getObjectsOnNamespaces();
 
     // New adapters return strings instead of classes.
-    let klassTypes = emberA(stringTypes).map((name) => {
+    let klassTypes = stringTypes.map((name) => {
```
Comment (wagenet) [inline packages/@ember/debug/data-adapter.ts:555]: These uses of `emberA` were unnecessary since `map` and `filter` are native methods.

File: packages/@ember/debug/data-adapter.ts [hunk 24]
```diff
@@ -544,22 +544,22 @@ export default class DataAdapter<T> extends EmberObject {
     @method getModelTypes
     @return {Array} Array of model types.
   */
-  getModelTypes(): NativeArray<{ klass: unknown; name: string }> {
+  getModelTypes(): Array<{ klass: unknown; name: string }> {
```
Comment (wagenet) [inline packages/@ember/debug/data-adapter.ts:547]: This is just documented as returning an array.

File: type-tests/preview/@ember/array-test/array.ts [hunk 25]
```diff
@@ -26,13 +27,11 @@ expectTypeOf(people.objectAt(0)).toEqualTypeOf<Person | undefined>();
 expectTypeOf(people.objectsAt([1, 2, 3])).toEqualTypeOf<Array<Person | undefined>>();
 
 expectTypeOf(people.filterBy('isHappy')).toMatchTypeOf<Person[]>();
-expectTypeOf(people.filterBy('isHappy')).toMatchTypeOf<MutableArray<Person>>();
+expectTypeOf(people.filterBy('isHappy')).toMatchTypeOf<NativeArray<Person>>();
```
Comment (wagenet) [inline type-tests/preview/@ember/array-test/array.ts:30]: NativeArray !== MutableArray

File: type-tests/preview/ember/ember-module-tests.ts [hunk 26]
```diff
@@ -153,7 +153,7 @@ expectTypeOf(Ember.Application.create()).toEqualTypeOf<Ember.Application>();
 expectTypeOf(new Ember.ApplicationInstance()).toEqualTypeOf<Ember.ApplicationInstance>();
 expectTypeOf(Ember.ApplicationInstance.create()).toEqualTypeOf<Ember.ApplicationInstance>();
 // Ember.Array
-const a1: Ember.Array<string> = Ember.A([]);
+const a1: Ember.NativeArray<string> = Ember.A([]);
```
Comment (wagenet) [inline type-tests/preview/ember/ember-module-tests.ts:156]: NativeArray !== EmberArray

File: types/preview/@ember/array/-private/native-array.d.ts [hunk 27]
```diff
@@ -1,22 +1,180 @@
...
   // Get an alias to the global Array type to use in inner scope below.
   type Array<T> = T[];
 
+  type AnyArray<T> = EmberArray<T> | Array<T>;
+
+  /**
+   * The final definition of NativeArray removes all native methods. This is the list of removed methods
+   * when run in Chrome 106.
+   */
+  type IGNORED_MUTABLE_ARRAY_METHODS =
```
Comment (wagenet) [inline types/preview/@ember/array/-private/native-array.d.ts:16]: The below should be the same as internal.

File: types/preview/@ember/array/index.d.ts [hunk 28]
```diff
@@ -4,6 +4,9 @@ declare module '@ember/array' {
   import Enumerable from '@ember/array/-private/enumerable';
   import NativeArray from '@ember/array/-private/native-array';
 
+  // We don't currently attempt to fully type-check compound keys
+  type CompoundPropertyKey<T> = `${keyof T & string}.${string}`;
```
Comment (wagenet) [inline types/preview/@ember/array/index.d.ts:8]: Bring these more in line with internal types.

File: types/preview/@ember/array/mutable.d.ts [hunk 29]
```diff
@@ -45,12 +45,12 @@ declare module '@ember/array/mutable' {
      * Pop object from array or nil if none are left. Works just like `pop()` but
      * it is KVO-compliant.
      */
-    popObject(): T;
+    popObject(): T | null | undefined;
```
Comment (wagenet) [inline types/preview/@ember/array/mutable.d.ts:48]: These types were incorrect before.

File: packages/@ember/array/index.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (chriskrycho) [reply packages/@ember/array/index.ts:523]: Ah, so this catches the case where we have `get(anArray, 'lol-nope')` and makes it not type check. In general, we haven’t tried to do that: people *do* (and from a public API can :upside_down:) stash unknown stuff on instances with `set` and then later `get` it, which should be "safe" (if not recommended).

File: packages/@ember/array/index.ts (hunk 4 above)
Comment (wagenet) [reply packages/@ember/array/index.ts]: Resolved

File: packages/@ember/array/index.ts (hunk 3 above)
Comment (wagenet) [reply packages/@ember/array/index.ts]: Resolved.

File: packages/@ember/array/index.ts [hunk 30]
```diff
@@ -792,6 +790,10 @@ interface EmberArray<T> extends Enumerable {
     @return {Object} Found item or `undefined`.
     @public
   */
+  find<S extends T, Target = void>(
```
Comment (chriskrycho) [inline packages/@ember/array/index.ts:793]: Note: conventionally/idiomatically it's `U` in a case like this (since T → U in the alphabet). Not a thing I care about changing, to be sure, just worth noting!

File: packages/@ember/array/index.ts [hunk 31]
```diff
@@ -1892,6 +1898,167 @@ const MutableArray = Mixin.create(EmberArray, MutableEnumerable, {
 /**
 @module ember
 */
+
+type AnyArray<T> = EmberArray<T> | Array<T>;
+
+/**
+ * The final definition of NativeArray removes all native methods. This is the list of removed methods
+ * when run in Chrome 106.
+ */
```
Comment (chriskrycho) [inline packages/@ember/array/index.ts:1907]: Note for posterity/future readers looking at this PR historically—we definitely need this, but we need even more to just get the heck rid of it, since this could in principle change dynamically over time.

File: packages/@ember/array/type-tests/mutable.ts [hunk 32]
```diff
@@ -1,63 +1,67 @@
...
+let originalArr = [foo];
+// This is not really the ideal way to set things up.
+MutableArray.apply(originalArr);
+let arr = originalArr as unknown as MutableArray<Foo>;
 
 expectTypeOf(arr).toMatchTypeOf<MutableArray<Foo>>();
 
 expectTypeOf(arr.replace(1, 1, [foo])).toEqualTypeOf<void>();
-// TODO: Why doesn't this fail?
+// @ts-expect-error invalid item
```
Comment (chriskrycho) [inline packages/@ember/array/type-tests/mutable.ts:19]: It's nice that all of these fail now the way we want them to. 👍🏼

File: packages/@ember/debug/container-debug-adapter.ts [hunk 33]
```diff
@@ -88,9 +86,9 @@ export default class ContainerDebugAdapter extends EmberObject {
...
```
Comment (chriskrycho) [inline packages/@ember/debug/container-debug-adapter.ts:91]: Hmm. Documentation is very apt to be incorrect in this space, though; folks who wrote the docs likely were not thinking about the differences (because the differences are subtle!). Let's avoid changing the behavior here—we can always do so in a later PR, but keeping types changes separate from behavior changes will help us avoid snafus.

File: packages/@ember/debug/data-adapter.ts (hunk 23 above)
Comment (chriskrycho) [reply packages/@ember/debug/data-adapter.ts:555]: On the one hand, this is *definitely* a change I'm excited to be able to make; on the other, my note here is the same as above. Let's do it in a separate PR so it's easy to trace back to if for some reason it ends up being an issue for folks.

File: packages/@ember/debug/data-adapter.ts [hunk 34]
```diff
@@ -571,8 +571,8 @@ export default class DataAdapter<T> extends EmberObject {
     @return {Array} Array of model type strings.
   */
   _getObjectsOnNamespaces() {
-    let namespaces = emberA(Namespace.NAMESPACES);
-    let types = emberA<string>();
+    let namespaces = Namespace.NAMESPACES;
+    let types: string[] = [];
```
Comment (chriskrycho) [inline packages/@ember/debug/data-adapter.ts:575]: Same here, presumably.

**Review by chriskrycho — CHANGES_REQUESTED** [review]
Couple of tweaks needed, but this is a really nice step forward. 💙

File: packages/@ember/array/index.ts (hunk 30 above)
Comment (wagenet) [reply packages/@ember/array/index.ts:793]: I think I just copied this from somewhere else :)

File: packages/@ember/array/type-tests/mutable.ts (hunk 32 above)
Comment (wagenet) [reply packages/@ember/array/type-tests/mutable.ts:19]: I think we just needed a better test item :)

**Review by chriskrycho — APPROVED** [review]
