### PR TITLE
[BUGFIX release] Ensure user lifecycle hooks are untracked

### LINKED ISSUE #19192: Backtracking assertion "more aggressive" in 3.22
### 🐞 Describe the Bug
The autotracking.mutation-after-consumption deprecation throws an error which breaks apps instead of a warning

### 🔬 Minimal Reproduction
https://ember-twiddle.com/c677ed60d39938c97ea7438d177c0ef3?openFiles=controllers.application%5C.js%2C

The console has to be opened to see the error

### 😕 Actual Behavior
Deprecation throws an error 

### 🤔 Expected Behavior
Deprecation is a warning

### 🌍 Environment

- Ember: 3.22.0
- Node.js/npm: -
- OS: -
- Browser: -

### PR DESCRIPTION
**Pull request by pzuraq**
When we refactored the VM to use autotracking internally, some lifecycle hooks were tracked that previously weren't on classic components. This PR ensures those hooks are no longer tracked, maintaining their previous behavior.

Fixes #19192

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
Should these be untracked though? Seems like they should at least emit a deprecation, no?

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
FWIW, we chatted RE: my concern above and decided that we did not want to introduce deprecations _at the moment_ for this. Specifically: resolving these deprecations would **largely** just be a waste of work (since the real path forward is migration to `@glimmer/component` which doesn't have these issues to begin with).

File: packages/@ember/-internals/glimmer/tests/integration/components/curly-components-test.js [hunk 1]
```diff
@@ -3732,6 +3732,75 @@ moduleFor(
...
+            this.foo;
+            this.foo = 123;
+          }
+
+          didDestroyElement() {
+            this.foo;
+            this.foo = 123;
+          }
+        },
+        template: '{{this.baz}}',
```
Comment (xg-wang) [inline packages/@ember/-internals/glimmer/tests/integration/components/curly-components-test.js:3791]: Dumb question when reading the diff, should it be `{{this.foo}}`?
