### PR TITLE
Fixes the bug with `fillIn` helper

### LINKED ISSUE #10034: fillIn() test helper does not focus its target element
The `fillIn()` helper fills in its target without ever causing the element to be focused. Here's a JSBin with a failing test:

http://emberjs.jsbin.com/sogesonedo/2/edit

This issue makes it difficult to test application logic that depends on the focused state. In my case, I have validation logic that triggers only when an input field loses focus: because the focus state of the input element never changes, my validation logic is never triggered in tests.

### PR DESCRIPTION
**Pull request by twokul**
Fixes #10034

### CODE REVIEW

**Comment by rwjblue** [comment]
Will need some test coverage to confirm.  I think the easiest thing to do would be to load an `{{input}}` and confirm its focus action fires when updated by the `fillIn` helper.

You can start with https://github.com/emberjs/ember.js/blob/9233641859cc3505e683f6bc3166ca27dffc54b2/packages/ember-testing/tests/helpers_test.js#L492-L513 as a basis...

File: packages/ember-testing/tests/helpers_test.js [hunk 1]
```diff
@@ -512,6 +512,33 @@ test("`fillIn` takes context into consideration", function() {
...
 });
 
+test("`fillIn` focuses on the element", function() {
+  expect(2);
+  var fillIn, find, visit, andThen;
+
+  App.IndexView = EmberView.extend({
+    template: compile('<div id="parent">{{input type="text" id="first"}}</div>'),
+    didInsertElement: function() {
+      this.$('#first').on('focusin', function() {
```
Comment (rwjblue) [inline packages/ember-testing/tests/helpers_test.js]: Can you instead just bind the `focus-in` action?  Something like http://emberjs.jsbin.com/rwjblue/193/edit.

Then you can assert that the action was called.

Comment (twokul) [inline packages/ember-testing/tests/helpers_test.js]: I just copied the way other tests were keeping track events. I do agree though that this more "real life" assertion.
