### PR TITLE
[BUGFIX] isEmpty on nested objects

### LINKED ISSUE #16878: Calling isEmpty on instances of ObjectProxy wrapping ArrayProxy throws Assertion Failed: You attempted to access the `length` property
While working on one of our projects, I encountered an error which I managed to boil down to the following:

```js
Ember.isEmpty(Ember.ObjectProxy.create({
  content: Ember.ArrayProxy.create({
    content: Ember.A([])
  })
}))
```

Looks like a regression caused by utilisation of ES5 getters, it worked in Ember 3.0.0.

It breaks for example `ember-changeset` with `ember-data-model-fragments`.

### PR DESCRIPTION
**Pull request by janvotava**
So ArrayProxy inside ObjectProxy works with ES5 getters and there's no `Assertion Failed: You attempted to access the 'length' property` error.

Fixes #16878

### CODE REVIEW

File: packages/ember-metal/lib/is_empty.ts [hunk 1]
```diff
@@ -52,18 +52,16 @@ export default function isEmpty(obj: any): boolean {
...
-  }
 
-  if (objectType === 'object') {
     let length = get(obj, 'length');
     if (typeof length === 'number') {
       return !length;
     }
   }
 
+  if (typeof obj.length === 'number' && objectType !== 'function') {
```
Comment (rwjblue) [inline packages/ember-metal/lib/is_empty.ts]: Hmm, do we even need this check anymore?

**Comment by sheebz45** [comment]
I didn’t do this

**Comment by locks** [comment]
@janvotava do you have some time to pick this back up? 😅

**Comment by wagenet** [comment]
@janvotava @locks I rebased this for you.

File: packages/ember-metal/lib/is_empty.ts (hunk 1 above)
Comment (wagenet) [reply packages/ember-metal/lib/is_empty.ts]: This is what allows an empty string (`''`) to be marked as empty.

**Comment by janvotava** [comment]
@locks I'm sorry. What exactly do you mean by that? 😅

**Comment by locks** [comment]
All is good, @wagenet took care of it :)
