### PR TITLE
[BUGFIX beta] Fix processing arguments in rerender

### LINKED ISSUE #12613: attrs not updating correctly for contextual components
Please see the console on this twiddle https://ember-twiddle.com/a8022eac7bbe8eb52801

_Edit_: Sorry, badly named issue. Not sure what the actual problem is just yet.

### PR DESCRIPTION
**Pull request by Serabe**
Rerendering a dot-syntax closure component failed to update the attributes due
to the shortcut being done too soon.

Fix #12613

### CODE REVIEW

File: packages/ember-htmlbars/tests/helpers/closure_component_test.js [hunk 1]
```diff
@@ -456,6 +456,52 @@ if (isEnabled('ember-contextual-components')) {
...
+                           {{/my-component}}
+                           <br>
+                           <button onclick={{action 'changeValue'}}>Change value</button>`);
+    component = Component.extend({
+      [OWNER]: owner,
+      template,
+      myProp: 1,
+      actions: {
+        changeValue() { this.incrementProperty(`myProp`); },
+      },
```
Comment (mixonic) [inline packages/ember-htmlbars/tests/helpers/closure_component_test.js]: Trailing comma

File: packages/ember-htmlbars/tests/helpers/closure_component_test.js [hunk 2]
```diff
@@ -456,6 +456,52 @@ if (isEnabled('ember-contextual-components')) {
...
   });
 
+  QUnit.test('renders with dot path and updates attributes', function() {
+
+    owner.register(
+      'component:my-nested-component',
+      Component.extend({
+        didReceiveAttrs() {
+          this.set('myProp', this.getAttr('my-parent-attr'));
+        },
```
Comment (mixonic) [inline packages/ember-htmlbars/tests/helpers/closure_component_test.js]: Trailing comma

File: packages/ember-htmlbars/tests/helpers/closure_component_test.js [hunk 3]
```diff
@@ -456,6 +456,52 @@ if (isEnabled('ember-contextual-components')) {
...
+                             {{api.my-nested-component}}
+                           {{/my-component}}
+                           <br>
+                           <button onclick={{action 'changeValue'}}>Change value</button>`);
+    component = Component.extend({
+      [OWNER]: owner,
+      template,
+      myProp: 1,
+      actions: {
+        changeValue() { this.incrementProperty(`myProp`); },
```
Comment (mixonic) [inline packages/ember-htmlbars/tests/helpers/closure_component_test.js]: Trailing comma

**Comment by rwjblue** [comment]
Aside from @mixonic's comments, this looks good.  Thanks for tackling @Serabe!

**Comment by Serabe** [comment]
Fixed everything. Thank you @mixonic and @rwjblue

**Comment by rwjblue** [comment]
Thanks again @Serabe !
