### PR TITLE
[BUGFIX release] Fix `Ember.computed.sum`

### LINKED ISSUE #12096: [REGRESSION] Ember.computed.sum + null
working 1.x: http://ember-twiddle.com/ead0375694c976377027

I believe 1.x is correct, as JS coerces `null` to `0` -> `Number(null) === 0`

This likely applies to other computed array  macros

### PR DESCRIPTION
**Pull request by duggiefresh**
Check to see if the `dependentKey` is an array, if not, then return
the `initialValue`.

Closes #12096

### CODE REVIEW

File: packages/ember-runtime/lib/computed/reduce_computed_macros.js [hunk 1]
```diff
@@ -13,7 +13,11 @@ import { isArray } from 'ember-runtime/utils';
 
 function reduceMacro(dependentKey, callback, initialValue) {
   return computed(`${dependentKey}.[]`, function() {
-    return get(this, dependentKey).reduce((previousValue, currentValue, index, array) => {
+    const arr = get(this, dependentKey);
+
+    if (!isArray(arr)) { return initialValue; }
```
Comment (stefanpenner) [inline packages/ember-runtime/lib/computed/reduce_computed_macros.js]: I believe this check should actually be

`(arr === null || arr === undefined)`

If `arr` is an object and doesn't have reduce we should throw, but not if it is just not an array or an array like.

Comment (duggiefresh) [inline packages/ember-runtime/lib/computed/reduce_computed_macros.js]: +1 That makes sense. Should it throw if `arr` is a string?

Comment (stefanpenner) [inline packages/ember-runtime/lib/computed/reduce_computed_macros.js]: > If arr is an object and doesn't have reduce we should throw,

it should likely throw if it is not an array and not an object.

Comment (duggiefresh) [inline packages/ember-runtime/lib/computed/reduce_computed_macros.js]: Cool, thanks for the feedback! Updated per review. :)

**Comment by rwjblue** [comment]
Thanks @duggiefresh!
